import type { Category, EquipmentId, Exercise } from "./types";

/**
 * Übungsbibliothek mit Equipment-Tags und Technik-Bezug.
 *
 * Wichtig:
 *   • `equipment` ist die ZWINGEND benötigte Ausrüstung — leeres Array
 *     bedeutet bodyweight-only.
 *   • Wenn nichts vom benötigten Equipment ausgewählt ist, schließt der
 *     Workout-Generator die Übung aus.
 *   • Bodyweight-Alternativen werden separat als eigene Übungen angelegt.
 */
export const EXERCISES: Exercise[] = [
  // ─── Warm-up ─────────────────────────────────────────────────────────────
  {
    id: "warmup_jump_rope",
    name: "Seilspringen",
    kind: "warmup",
    category: "any",
    difficulty: "any",
    durationSeconds: 180,
    restSeconds: 30,
    defaultRounds: 3,
    intensity: "medium",
    equipment: ["jump-rope"],
    focus: ["Cardio", "Footwork", "Koordination"],
    cues: ["Hohe Knie", "Schnelle Füße", "Atmung kontrollieren"],
  },
  {
    id: "warmup_shadowbox",
    name: "Schattenboxen",
    kind: "warmup",
    category: "boxing",
    difficulty: "any",
    durationSeconds: 180,
    restSeconds: 30,
    defaultRounds: 3,
    intensity: "medium",
    equipment: [],
    techniqueIds: ["boxing_jab", "boxing_cross", "boxing_hook"],
    focus: ["Footwork", "Kombinationen", "Kopfbewegung"],
    cues: ["Hände hoch", "Hüftrotation", "Atmen"],
  },
  {
    id: "warmup_jumping_jacks",
    name: "Jumping Jacks",
    kind: "warmup",
    category: "any",
    difficulty: "any",
    durationSeconds: 60,
    restSeconds: 15,
    defaultRounds: 3,
    intensity: "low",
    equipment: [],
    focus: ["Cardio", "Aufwärmen"],
    cues: ["Tempo halten", "Vollständige Bewegung"],
  },
  {
    id: "warmup_solo_drills_bjj",
    name: "BJJ Solo-Drills",
    kind: "warmup",
    category: "bjj",
    difficulty: "any",
    durationSeconds: 180,
    restSeconds: 30,
    defaultRounds: 3,
    intensity: "low",
    equipment: ["mat"],
    techniqueIds: ["bjj_hip_escape", "bjj_bridge_roll", "bjj_technical_standup"],
    focus: ["Mobility", "BJJ-Bewegung"],
    cues: ["Saubere Mechanik", "Beidseitig", "Hüfte aktiv"],
  },
  {
    id: "warmup_stance_motion",
    name: "Stance & Motion Drill",
    kind: "warmup",
    category: "wrestling",
    difficulty: "any",
    durationSeconds: 120,
    restSeconds: 30,
    defaultRounds: 3,
    intensity: "medium",
    equipment: ["mat"],
    techniqueIds: ["wrestling_stance", "wrestling_level_change"],
    focus: ["Wrestling-Stand", "Level Changes"],
    cues: ["Hüfte tief", "Hände aktiv", "Kein Kreuzen"],
  },

  // ─── Technik-Übungen Boxing ──────────────────────────────────────────────
  {
    id: "boxing_jab_cross_bag",
    name: "Jab-Cross am Sandsack",
    kind: "technique",
    category: "boxing",
    difficulty: "anfaenger",
    durationSeconds: 180,
    restSeconds: 60,
    defaultRounds: 3,
    intensity: "high",
    equipment: ["heavy-bag"],
    techniqueIds: ["boxing_jab", "boxing_cross"],
    focus: ["Combo-Timing", "Power"],
    cues: ["Schnelle Hände", "Hüftdreh", "Deckung"],
  },
  {
    id: "boxing_jab_cross_hook_bag",
    name: "1-2-3 am Sandsack",
    kind: "technique",
    category: "boxing",
    difficulty: "fortgeschritten",
    durationSeconds: 180,
    restSeconds: 60,
    defaultRounds: 4,
    intensity: "high",
    equipment: ["heavy-bag"],
    techniqueIds: ["boxing_jab_cross_hook"],
    focus: ["3-Schlag-Combo", "Power"],
    cues: ["Saubere Mechanik vor Power", "Volle Hüftrotation auf 3"],
  },
  {
    id: "boxing_pad_combos",
    name: "Pratzenarbeit Boxing-Combos",
    kind: "technique",
    category: "boxing",
    difficulty: "any",
    durationSeconds: 180,
    restSeconds: 60,
    defaultRounds: 4,
    intensity: "high",
    equipment: ["pads"],
    techniqueIds: ["boxing_jab", "boxing_cross", "boxing_hook"],
    focus: ["Timing", "Reaktion", "Power"],
    cues: ["Augen am Coach", "Sofort zurück in Deckung"],
  },
  {
    id: "boxing_shadow_combos",
    name: "Shadowbox-Kombinationen",
    kind: "technique",
    category: "boxing",
    difficulty: "any",
    durationSeconds: 180,
    restSeconds: 60,
    defaultRounds: 3,
    intensity: "medium",
    equipment: [],
    techniqueIds: ["boxing_jab", "boxing_cross", "boxing_hook", "boxing_slip"],
    focus: ["Technik", "Kopfbewegung"],
    cues: ["Wie ein echter Kampf", "Atmung", "Mehr Variation"],
  },
  {
    id: "boxing_defense_drill",
    name: "Defense Drill (Slip & Roll)",
    kind: "technique",
    category: "boxing",
    difficulty: "any",
    durationSeconds: 180,
    restSeconds: 60,
    defaultRounds: 3,
    intensity: "medium",
    equipment: [],
    techniqueIds: ["boxing_slip", "boxing_roll"],
    focus: ["Kopfbewegung", "Distanz"],
    cues: ["Augen am Gegner", "Knie weich"],
  },

  // ─── Technik-Übungen Wrestling ───────────────────────────────────────────
  {
    id: "wrestling_penetration_drill",
    name: "Penetration Step Drill",
    kind: "technique",
    category: "wrestling",
    difficulty: "anfaenger",
    durationSeconds: 90,
    restSeconds: 30,
    defaultRounds: 4,
    intensity: "high",
    equipment: ["mat"],
    techniqueIds: ["wrestling_penetration_step"],
    focus: ["Explosivität", "Tiefe"],
    cues: ["Knie zwischen die Beine", "Kopf hoch"],
  },
  {
    id: "wrestling_single_leg_drill",
    name: "Single-Leg Reps",
    kind: "technique",
    category: "wrestling",
    difficulty: "anfaenger",
    durationSeconds: 120,
    restSeconds: 30,
    defaultRounds: 3,
    intensity: "high",
    equipment: ["mat"],
    techniqueIds: ["wrestling_single_leg"],
    focus: ["Takedown-Setup", "Beidseitig"],
    cues: ["Kopf an die Innenseite", "Hüfte ankreuzen"],
  },
  {
    id: "wrestling_sprawl_drill",
    name: "Sprawl Drill",
    kind: "technique",
    category: "wrestling",
    difficulty: "anfaenger",
    durationSeconds: 30,
    restSeconds: 15,
    defaultRounds: 5,
    intensity: "high",
    equipment: ["mat"],
    techniqueIds: ["wrestling_sprawl"],
    focus: ["Takedown-Verteidigung"],
    cues: ["Hüfte fällt", "Brust auf Schultern"],
  },
  {
    id: "wrestling_double_leg_drill",
    name: "Double-Leg Reps",
    kind: "technique",
    category: "wrestling",
    difficulty: "fortgeschritten",
    durationSeconds: 120,
    restSeconds: 30,
    defaultRounds: 3,
    intensity: "high",
    equipment: ["mat"],
    techniqueIds: ["wrestling_double_leg"],
    focus: ["Takedown-Power"],
    cues: ["Tiefer Schuss", "Kopf hoch"],
  },

  // ─── Technik-Übungen BJJ ─────────────────────────────────────────────────
  {
    id: "bjj_shrimp_drill",
    name: "Shrimp-Drill",
    kind: "technique",
    category: "bjj",
    difficulty: "anfaenger",
    durationSeconds: 60,
    restSeconds: 15,
    defaultRounds: 3,
    intensity: "medium",
    equipment: ["mat"],
    techniqueIds: ["bjj_hip_escape"],
    focus: ["Hüftbewegung", "Recovery"],
    cues: ["Schulter und Ellbogen flach", "Hüfte explosiv"],
  },
  {
    id: "bjj_armbar_reps",
    name: "Armbar Reps",
    kind: "technique",
    category: "bjj",
    difficulty: "fortgeschritten",
    durationSeconds: 120,
    restSeconds: 30,
    defaultRounds: 3,
    intensity: "low",
    equipment: ["mat"],
    techniqueIds: ["bjj_armbar_from_guard"],
    focus: ["Submission-Mechanik"],
    cues: ["Hüfte ausschwenken", "Knie schließen"],
  },
  {
    id: "bjj_triangle_reps",
    name: "Triangle Reps",
    kind: "technique",
    category: "bjj",
    difficulty: "fortgeschritten",
    durationSeconds: 120,
    restSeconds: 30,
    defaultRounds: 3,
    intensity: "low",
    equipment: ["mat"],
    techniqueIds: ["bjj_triangle_from_guard"],
    focus: ["Choke-Mechanik", "Winkel"],
    cues: ["Arm in / Arm out", "Hüfte zur Seite"],
  },
  {
    id: "bjj_positional_sparring",
    name: "Positional Sparring",
    kind: "technique",
    category: "bjj",
    difficulty: "any",
    durationSeconds: 180,
    restSeconds: 60,
    defaultRounds: 4,
    intensity: "high",
    equipment: ["mat"],
    focus: ["Live-Application"],
    cues: ["Position vor Submission", "Atmen"],
  },

  // ─── Technik-Übungen Muay Thai ───────────────────────────────────────────
  {
    id: "muaythai_kick_bag",
    name: "Roundhouse-Kicks am Sandsack",
    kind: "technique",
    category: "muay-thai",
    difficulty: "anfaenger",
    durationSeconds: 120,
    restSeconds: 30,
    defaultRounds: 4,
    intensity: "high",
    equipment: ["heavy-bag"],
    techniqueIds: ["muaythai_roundhouse"],
    focus: ["Kick-Power", "Hüftrotation"],
    cues: ["Standfuß drehen", "Schienbein, nicht Spann"],
  },
  {
    id: "muaythai_teep_bag",
    name: "Teep-Drill am Sandsack",
    kind: "technique",
    category: "muay-thai",
    difficulty: "anfaenger",
    durationSeconds: 120,
    restSeconds: 30,
    defaultRounds: 3,
    intensity: "medium",
    equipment: ["heavy-bag"],
    techniqueIds: ["muaythai_teep"],
    focus: ["Distanz-Kontrolle"],
    cues: ["Knie hoch", "Hüfte schiebt"],
  },
  {
    id: "muaythai_knee_clinch",
    name: "Knee Strikes (Clinch oder Sandsack)",
    kind: "technique",
    category: "muay-thai",
    difficulty: "anfaenger",
    durationSeconds: 120,
    restSeconds: 30,
    defaultRounds: 3,
    intensity: "high",
    equipment: ["heavy-bag"],
    techniqueIds: ["muaythai_knee", "muaythai_clinch_basic"],
    focus: ["Nahdistanz-Power"],
    cues: ["Hüfte nach vorn", "Spitze des Knies"],
  },
  {
    id: "muaythai_pad_combos",
    name: "Pratzen-Kombinationen Muay Thai",
    kind: "technique",
    category: "muay-thai",
    difficulty: "fortgeschritten",
    durationSeconds: 180,
    restSeconds: 60,
    defaultRounds: 4,
    intensity: "high",
    equipment: ["pads"],
    techniqueIds: ["muaythai_teep", "muaythai_low_kick", "muaythai_roundhouse"],
    focus: ["Timing", "Combo-Flow"],
    cues: ["Folge dem Coach", "Volle Combos"],
  },
  {
    id: "muaythai_shin_conditioning",
    name: "Schienbein-Konditionierung",
    kind: "technique",
    category: "muay-thai",
    difficulty: "any",
    durationSeconds: 120,
    restSeconds: 30,
    defaultRounds: 3,
    intensity: "medium",
    equipment: ["heavy-bag"],
    techniqueIds: ["muaythai_low_kick"],
    focus: ["Konditionierung", "Toleranz"],
    cues: ["Kontrollierte Power", "Saubere Technik"],
  },

  // ─── Konditionierung ─────────────────────────────────────────────────────
  {
    id: "cond_burpees",
    name: "Burpees",
    kind: "conditioning",
    category: "any",
    difficulty: "any",
    durationSeconds: 60,
    restSeconds: 30,
    defaultRounds: 3,
    intensity: "high",
    equipment: [],
    focus: ["Cardio", "Ganzkörper"],
    cues: ["Volle Bewegung", "Tempo halten"],
  },
  {
    id: "cond_sit_ups",
    name: "Sit-ups",
    kind: "conditioning",
    category: "any",
    difficulty: "any",
    durationSeconds: 60,
    restSeconds: 20,
    defaultRounds: 3,
    intensity: "medium",
    equipment: [],
    focus: ["Core"],
  },
  {
    id: "cond_kb_swings_10",
    name: "Kettlebell Swings (10kg)",
    kind: "conditioning",
    category: "any",
    difficulty: "any",
    durationSeconds: 60,
    restSeconds: 30,
    defaultRounds: 3,
    intensity: "high",
    equipment: ["kettlebell-10"],
    focus: ["Hüft-Power", "Core"],
    cues: ["Hüfte snappt", "Arme nur Tragefunktion"],
  },
  {
    id: "cond_kb_swings_20",
    name: "Heavy Kettlebell Swings (20kg)",
    kind: "conditioning",
    category: "any",
    difficulty: "fortgeschritten",
    durationSeconds: 45,
    restSeconds: 30,
    defaultRounds: 3,
    intensity: "high",
    equipment: ["kettlebell-20"],
    focus: ["Hüft-Power", "Kraft"],
    cues: ["Form first", "Atemrhythmus"],
  },
  {
    id: "cond_dumbbell_punches",
    name: "Kurzhantel-Punches",
    kind: "conditioning",
    category: "boxing",
    difficulty: "any",
    durationSeconds: 60,
    restSeconds: 30,
    defaultRounds: 3,
    intensity: "high",
    equipment: ["dumbbell"],
    focus: ["Schulter-Ausdauer", "Punches"],
    cues: ["Saubere Mechanik", "Hand zurück"],
  },
  {
    id: "cond_med_ball_slams",
    name: "Medizinball Slams",
    kind: "conditioning",
    category: "any",
    difficulty: "any",
    durationSeconds: 45,
    restSeconds: 30,
    defaultRounds: 3,
    intensity: "high",
    equipment: ["medicine-ball-7"],
    focus: ["Ganzkörper-Power", "Core"],
    cues: ["Ball über Kopf", "Volle Hüfte"],
  },
  {
    id: "cond_pushups",
    name: "Push-ups",
    kind: "conditioning",
    category: "any",
    difficulty: "any",
    durationSeconds: 60,
    restSeconds: 30,
    defaultRounds: 3,
    intensity: "medium",
    equipment: [],
    focus: ["Brust", "Schultern", "Core"],
  },
  {
    id: "cond_squats",
    name: "Bodyweight Squats",
    kind: "conditioning",
    category: "any",
    difficulty: "any",
    durationSeconds: 60,
    restSeconds: 30,
    defaultRounds: 3,
    intensity: "medium",
    equipment: [],
    focus: ["Beine", "Hüfte"],
  },
  {
    id: "cond_band_pull_aparts",
    name: "Band Pull-aparts",
    kind: "conditioning",
    category: "any",
    difficulty: "any",
    durationSeconds: 45,
    restSeconds: 20,
    defaultRounds: 3,
    intensity: "low",
    equipment: ["resistance-band"],
    focus: ["Rücken", "Schulter-Aktivierung"],
  },
  {
    id: "cond_wrestler_ladder",
    name: "Sprawl-Sprint Ladder",
    kind: "conditioning",
    category: "wrestling",
    difficulty: "fortgeschritten",
    durationSeconds: 120,
    restSeconds: 60,
    defaultRounds: 3,
    intensity: "high",
    equipment: ["mat"],
    focus: ["Wrestler-Cardio"],
    cues: ["Volle Sprawls", "Sofortige Sprints"],
  },

  // ─── Cooldown ────────────────────────────────────────────────────────────
  {
    id: "cooldown_stretch",
    name: "Stretching & Mobility",
    kind: "cooldown",
    category: "any",
    difficulty: "any",
    durationSeconds: 300,
    restSeconds: 0,
    defaultRounds: 1,
    intensity: "low",
    equipment: [],
    focus: ["Recovery", "Mobility"],
    cues: ["Atmung tief", "Locker bleiben"],
  },
  {
    id: "cooldown_breathing",
    name: "Box Breathing",
    kind: "cooldown",
    category: "any",
    difficulty: "any",
    durationSeconds: 180,
    restSeconds: 0,
    defaultRounds: 1,
    intensity: "low",
    equipment: [],
    focus: ["Atmung", "Recovery"],
    cues: ["4 ein, 4 halten, 4 aus, 4 halten"],
  },
];

const BY_ID = new Map<string, Exercise>(EXERCISES.map((e) => [e.id, e]));

export function getExerciseById(id: string): Exercise | undefined {
  return BY_ID.get(id);
}

/** Filtert Übungen, deren benötigtes Equipment komplett verfügbar ist. */
export function exercisesWithEquipment(
  available: EquipmentId[],
): Exercise[] {
  const set = new Set(available);
  return EXERCISES.filter((e) => {
    if (e.equipment.length === 0) return true;
    return e.equipment.every((eq) => set.has(eq));
  });
}

export function exercisesForCategory(
  cat: Category,
  options: { includeAny?: boolean } = { includeAny: true },
): Exercise[] {
  return EXERCISES.filter(
    (e) =>
      e.category === cat ||
      (options.includeAny !== false && e.category === "any"),
  );
}
