import type { Technique } from "../types";

export const BJJ_TECHNIQUES: Technique[] = [
  // ─── Anfänger ────────────────────────────────────────────────────────────
  {
    id: "bjj_hip_escape",
    slug: "hip-escape",
    name: "Hip Escape (Shrimp)",
    category: "bjj",
    difficulty: "anfaenger",
    description:
      "Die fundamentalste Bewegung im BJJ. Hüfte explosiv aus der Linie schieben — Basis für jede Escape, Recovery und Sweep.",
    steps: [
      "Auf dem Rücken liegen, Knie angezogen, Füße flach auf der Matte.",
      "Eine Schulter und Ellbogen flach auf die Matte drücken.",
      "Mit den Füßen explosiv abdrücken, Hüfte schiebt zur Seite.",
      "Beide Beine kommen zur Brust ran.",
      "Wieder absetzen — fertig zum nächsten Shrimp.",
    ],
    commonMistakes: [
      "Schulter wird mitgenommen → Gegner folgt einfach.",
      "Hüfte hebt nicht ab → reines 'Ableger-Schieben'.",
      "Knie-Ellbogen-Verbindung fehlt → keine Defensive.",
      "Zu langsam — Shrimp muss explosiv sein.",
    ],
    usage:
      "Aus Mount, Side Control, Knee-on-Belly entkommen. Setup für Guard-Recovery.",
    equipment: ["mat", "bodyweight"],
    video: {
      url: "https://www.youtube.com/embed/yiA-UfMxq8s",
      source: "YouTube",
      license: "YouTube-Embed",
      attribution: "BJJ Tutorial",
    },
    relatedTechniqueIds: ["bjj_bridge_roll", "bjj_mount_escape"],
    nextTechniqueId: "bjj_bridge_roll",
    disciplines: ["bjj", "mma", "wrestling"],
    trainingArea: ["escapes", "guard"],
    role: "core",
    level: "anfaenger",
    alternativeNames: ["Shrimp", "Elbow-Knee Escape", "Hüftflucht"],
    coachingCues: [
      "Hüfte muss von der Matte abheben — kein flaches Schieben.",
      "Eine Schulter bleibt am Boden als Pivot-Punkt.",
      "Explosiv: Schusskraft aus den Füßen.",
      "Direkt anschließend Beine zur Brust ziehen.",
    ],
    safetyNotes: [],
    useCases: [
      "Mount-Escape mit anschließender Guard-Recovery.",
      "Side-Control-Escape: Shrimp weg, Bein einbringen.",
      "Drill für BJJ-Aufwärmprogramm.",
    ],
    priorityScore: 10,
    frequencyScore: 10,
    diversityGroup: "escape-movement",
    videoSearchQuery: "Hip Escape Shrimp BJJ tutorial",
  },
  {
    id: "bjj_technical_standup",
    slug: "technical-standup",
    name: "Technical Stand-up",
    category: "bjj",
    difficulty: "anfaenger",
    description:
      "Sicheres Aufstehen vom Boden — eine Hand am Boden, Augen am Gegner. Verhindert, dass der Gegner einen Schlag oder Takedown setzt.",
    steps: [
      "Aus dem Sitz: eine Hand hinter den Körper auf die Matte.",
      "Anderes Bein anziehen, Fuß zwischen Hand und Hüfte.",
      "Andere Hand schützt das Gesicht.",
      "Mit Hand und Fuß abdrücken, Körper hebt sich.",
      "Hinteres Bein schwingt nach unten in Boxstellung.",
    ],
    commonMistakes: [
      "Beide Hände am Boden → Schlaghand fehlt zur Verteidigung.",
      "Augen am Boden → keine Reaktion auf Gegner.",
      "Zu langsam — Gegner schließt die Distanz.",
      "Nach dem Aufstehen offene Stellung — kein Übergang in Guard.",
    ],
    usage:
      "Vom Boden zurück auf die Beine kommen, ohne sich für Schläge oder Takedowns zu öffnen. Wichtig in MMA und Selbstverteidigung.",
    equipment: ["mat", "bodyweight"],
    relatedTechniqueIds: ["bjj_hip_escape"],
    disciplines: ["bjj", "mma", "self-defense"],
    trainingArea: ["escapes", "transitions"],
    role: "core",
    level: "anfaenger",
    alternativeNames: ["Safe Stand-up", "MMA Stand-up"],
    coachingCues: [
      "Eine Hand am Boden, eine Hand schützt das Gesicht — immer.",
      "Augen am Gegner während des gesamten Aufstehens.",
      "Schnell: Aufstehen ist eine Übergangsphase, keine Pause.",
      "In Kampfstellung landen — nicht in offener Position.",
    ],
    safetyNotes: [
      "Im MMA besonders wichtig: Aufstehen mit gesenktem Kopf = Knietreffer.",
    ],
    useCases: [
      "Nach einem Takedown wieder aufstehen.",
      "Aus dem Guard aufstehen, wenn Gegner zu weit weg ist.",
      "MMA-Grundlage: sicherer Übergang Boden→Stand.",
    ],
    priorityScore: 9,
    frequencyScore: 8,
    diversityGroup: "escape-movement",
    videoSearchQuery: "Technical standup BJJ MMA tutorial",
  },
  {
    id: "bjj_bridge_roll",
    slug: "bridge-roll",
    name: "Bridge & Roll",
    category: "bjj",
    difficulty: "anfaenger",
    description:
      "Klassische Mount-Escape: durch eine starke Brücke und einen Roll wird der Gegner über den Kopf geworfen.",
    steps: [
      "Aus der Mount-Verteidigung: einen Arm des Gegners trappen.",
      "Auf der gleichen Seite ein Bein des Gegners trappen (Fuß auf Wade).",
      "Hüfte explosiv nach oben in eine starke Brücke.",
      "Auf die getrapte Seite rollen — Gegner landet auf dem Rücken.",
      "Aus der Closed Guard sofort weiterarbeiten.",
    ],
    commonMistakes: [
      "Kein Fuß-Trap → Gegner postet das Bein und blockt den Roll.",
      "Brücke nicht hoch genug → kein Lift.",
      "Falsche Seite gerollt → Gegner bleibt drauf.",
      "Arm nicht getrapt → Gegner postet die Hand.",
    ],
    usage:
      "Erster Mount-Escape, den jeder lernt. Auch im MMA gegen Ground-and-Pound essentiell.",
    equipment: ["mat"],
    relatedTechniqueIds: ["bjj_mount_escape", "bjj_hip_escape"],
    nextTechniqueId: "bjj_mount_escape",
    disciplines: ["bjj", "mma", "wrestling"],
    trainingArea: ["escapes", "transitions"],
    role: "core",
    level: "anfaenger",
    alternativeNames: ["Upa Escape", "Bridge & Roll Mount Escape"],
    coachingCues: [
      "Zuerst trappen, dann brücken — ohne Trap kein Roll.",
      "Brücke so hoch wie möglich: Nacken-Schultern tragen das Gewicht.",
      "Roll zu der Seite, die getrappt ist — nicht andersherum.",
      "Sofort Guard schließen nach dem Roll.",
    ],
    safetyNotes: [
      "Brücke belastet die Halswirbelsäule — auf Matten trainieren.",
    ],
    useCases: [
      "Standard-Mount-Escape wenn Ellbogen-Escape geblockt wird.",
      "MMA: Wenn Gegner Ground-and-Pound ansetzt.",
      "Kombination: Bridge & Roll + Ellbogen-Escape wechseln.",
    ],
    priorityScore: 9,
    frequencyScore: 8,
    diversityGroup: "escape-movement",
    videoSearchQuery: "Bridge Roll mount escape BJJ tutorial",
  },
  {
    id: "bjj_closed_guard",
    slug: "closed-guard",
    name: "Closed Guard",
    category: "bjj",
    difficulty: "anfaenger",
    description:
      "Die fundamentale Guard: Beine um den Gegner geschlossen, Hüfte aktiv, Hände kontrollieren Arme oder Kragen.",
    steps: [
      "Auf dem Rücken: Beine um die Hüfte des Gegners.",
      "Knöchel kreuzen — Beine fest geschlossen.",
      "Eine Hand am Handgelenk des Gegners, andere am Kragen oder Hinterkopf.",
      "Hüfte aktiv — niemals stillliegen.",
      "Aus der Closed Guard arbeiten: Sweeps, Submissions oder Distanz.",
    ],
    commonMistakes: [
      "Beine offen → Guard wird durchgesetzt.",
      "Passive Hüfte → Gegner postet auf die Brust.",
      "Hände unten → keine Kontrolle des Oberkörpers.",
      "Auf den Rücken gelegt → Mount-Threat.",
    ],
    usage:
      "Zentrale Position für Sweeps und Submissions. Guard ist die Grundlage des BJJ.",
    equipment: ["mat"],
    relatedTechniqueIds: ["bjj_armbar_from_guard", "bjj_triangle_from_guard"],
    nextTechniqueId: "bjj_scissor_sweep",
    disciplines: ["bjj", "mma"],
    trainingArea: ["guard", "submissions", "sweeps"],
    role: "core",
    level: "anfaenger",
    alternativeNames: ["Full Guard", "Geschlossene Guard"],
    coachingCues: [
      "Beine fest und aktiv — Hüfte ist die Waffe.",
      "Hände kontrollieren immer einen Arm des Gegners.",
      "Hüfte aktiv halten: kippen und Winkel suchen.",
      "Von der Guard aus greifen, nicht warten.",
    ],
    safetyNotes: [],
    useCases: [
      "Ausgangspunkt für Armbar, Triangle, Omoplata.",
      "Kontrolle gegen einen drückenden Gegner von unten.",
      "MMA: Submissions aus der Guard stoppen Stand-Up-Schläge.",
    ],
    priorityScore: 10,
    frequencyScore: 9,
    diversityGroup: "guard-position",
    videoSearchQuery: "Closed guard BJJ basics tutorial",
  },
  {
    id: "bjj_mount_escape",
    slug: "mount-escape",
    name: "Mount Escape (Elbow Escape)",
    category: "bjj",
    difficulty: "anfaenger",
    description:
      "Aus der Mount durch wiederholte Hip Escapes auf eine Seite, das Knie des Gegners blocken und in die Half/Closed Guard recovern.",
    steps: [
      "Eine Schulter und Ellbogen flach auf die Matte.",
      "Hüfte explosiv zur Seite shrimpen.",
      "Knie zur Brust, dann zwischen sich und den Gegner schieben.",
      "Mit dem Fuß das Knie des Gegners auf die Außenseite hooken.",
      "Weiter shrimpen → Half Guard oder Closed Guard.",
    ],
    commonMistakes: [
      "Schulter mitgenommen → Gegner folgt mit der Mount.",
      "Knie nicht zwischen die Körper → Gegner sitzt weiter drauf.",
      "Fuß hooked nicht → Bein wird wieder mitgenommen.",
      "Zu wenig Shrimps — Mount-Escape ist meistens 2-3 Shrimps.",
    ],
    usage:
      "Standard-Escape aus der Mount, wenn Bridge & Roll nicht funktioniert.",
    equipment: ["mat"],
    video: {
      url: "https://www.youtube.com/embed/5Y1CahWUA_s",
      source: "YouTube",
      license: "YouTube-Embed",
      attribution: "BJJ Tutorial",
    },
    relatedTechniqueIds: ["bjj_bridge_roll", "bjj_hip_escape"],
    disciplines: ["bjj", "mma"],
    trainingArea: ["escapes", "guard"],
    role: "core",
    level: "anfaenger",
    alternativeNames: ["Elbow-Knee Escape", "Elbow Mount Escape"],
    coachingCues: [
      "Schulter als Anker — Hüfte shrimpt, Schulter bleibt.",
      "Mehrfach shrimpen — nicht nach einem Shrimp aufgeben.",
      "Knie-Einbringen: Fuß hooken sobald Knie dazwischen ist.",
      "Ziel: Half Guard oder Closed Guard — nicht einfach flüchten.",
    ],
    safetyNotes: [],
    useCases: [
      "Mount-Escape als Alternative zu Bridge & Roll.",
      "Kombination beider Escapes: wechseln wenn eine geblockt wird.",
      "MMA: Ground-and-Pound stoppen durch Guard-Recovery.",
    ],
    priorityScore: 9,
    frequencyScore: 8,
    diversityGroup: "escape-movement",
    videoSearchQuery: "Elbow escape mount BJJ tutorial",
  },
  {
    id: "bjj_side_control_escape",
    slug: "side-control-escape",
    name: "Side-Control Escape",
    category: "bjj",
    difficulty: "anfaenger",
    description:
      "Aus Side Control durch Frame, Hip Escape und Underhook in Guard-Recovery oder zurück auf die Knie.",
    steps: [
      "Frames bauen: Unterarm an den Hals, andere Hand zur Hüfte.",
      "Hüfte explosiv zur Wand-Seite shrimpen.",
      "Bein zwischen sich und Gegner einbringen.",
      "Underhook auf der Far-Side suchen.",
      "Recovery in Half Guard oder zurück auf alle Viere (Turtle).",
    ],
    commonMistakes: [
      "Keine Frames → Gegner crusht den Kopf.",
      "Falsche Shrimp-Richtung — von Gegner weg, nicht zu ihm.",
      "Bein klein bleibt nicht eingehakt → Side Control bleibt.",
      "Aufgegeben — Side-Control-Escape ist mühsam, aber lernbar.",
    ],
    usage:
      "Eine der schwierigsten Positionen zu entkommen. Tägliches Drilling ist Pflicht.",
    equipment: ["mat"],
    relatedTechniqueIds: ["bjj_hip_escape"],
    disciplines: ["bjj", "mma"],
    trainingArea: ["escapes", "transitions"],
    role: "core",
    level: "anfaenger",
    alternativeNames: ["Side Control Escape", "Frame Escape"],
    coachingCues: [
      "Frame zuerst: ohne Frame kein Shrimp möglich.",
      "Zur Wand shrimpen, nicht weg vom Gegner.",
      "Underhook ist das Ziel — mit Underhook kommt man auf die Knie.",
      "Kontinuierlich arbeiten — keine Pause im Escape.",
    ],
    safetyNotes: [],
    useCases: [
      "Side Control Escape → Half Guard Recovery.",
      "Frame + Shrimp → Turtle Position → Stand-Up.",
      "MMA: Side Control Escape verhindern Strikes von der Seite.",
    ],
    priorityScore: 8,
    frequencyScore: 8,
    diversityGroup: "escape-movement",
    videoSearchQuery: "Side control escape BJJ tutorial",
  },

  // ─── Fortgeschritten ─────────────────────────────────────────────────────
  {
    id: "bjj_armbar_from_guard",
    slug: "armbar-from-guard",
    name: "Armbar from Guard",
    category: "bjj",
    difficulty: "fortgeschritten",
    description:
      "Klassische Submission aus der Closed Guard. Hüfte aushängen, Bein über den Kopf, Hebel auf den Ellbogen.",
    steps: [
      "Aus der Closed Guard: Arm des Gegners isolieren (z. B. mit C-Grip).",
      "Hüfte zur Seite des isolierten Arms ausschwenken — 90° zum Gegner.",
      "Eines der Beine über den Kopf des Gegners.",
      "Knie schließen, Daumen des Gegners zeigt nach oben.",
      "Hüfte heben → Hebel auf den Ellbogen → Submission.",
    ],
    commonMistakes: [
      "Daumen des Gegners zeigt nach unten → kein Hebel.",
      "Knie nicht zusammen → Gegner zieht Arm raus.",
      "Hüfte nicht ausgeschwenkt → kein Winkel.",
      "Zu langsam → Gegner stackt und entkommt.",
    ],
    usage:
      "Eine der ältesten und sichersten Submissions im BJJ. Pflicht-Technik für jeden Blue Belt.",
    equipment: ["mat"],
    video: {
      url: "https://www.youtube.com/embed/ybdyDkzfQG8",
      source: "YouTube",
      license: "YouTube-Embed",
      attribution: "BJJ Tutorial",
    },
    relatedTechniqueIds: ["bjj_closed_guard", "bjj_triangle_from_guard"],
    nextTechniqueId: "bjj_triangle_from_guard",
    disciplines: ["bjj", "mma"],
    trainingArea: ["submissions", "guard"],
    role: "core",
    level: "aufbau",
    alternativeNames: ["Juji-Gatame", "Arm Bar", "Armhebel"],
    coachingCues: [
      "Hüfte ausschwenken: 90° zum Gegner, nicht parallel.",
      "Daumen des Gegners muss nach oben zeigen.",
      "Knie schließen wie eine Schere — Arm kann nicht raus.",
      "Hüfte heben statt nach hinten ziehen.",
    ],
    safetyNotes: [
      "Im Training langsam aufbauen — Ellbogen-Hyperextension passiert schnell.",
    ],
    useCases: [
      "Submission wenn Gegner Arm zur Mitte streckt.",
      "Armbar als Antwort auf einen defensiven Gegner in der Guard.",
      "MMA: Armbar wenn Gegner sich auf Punches aus der Guard konzentriert.",
    ],
    priorityScore: 10,
    frequencyScore: 9,
    diversityGroup: "arm-submission",
    videoSearchQuery: "Armbar from guard BJJ tutorial",
  },
  {
    id: "bjj_triangle_from_guard",
    slug: "triangle-from-guard",
    name: "Triangle from Guard",
    category: "bjj",
    difficulty: "fortgeschritten",
    description:
      "Choke mit den Beinen — ein Arm in, ein Arm out, Bein um den Hals, andere Knie blockt.",
    steps: [
      "Aus der Closed Guard: einen Arm des Gegners durchziehen, anderen draußen lassen.",
      "Eigenes Bein der Arm-In-Seite über den Hals des Gegners.",
      "Anderes Knie unter das Knie der ersten Bein-Position klemmen.",
      "Winkel suchen — Hüfte zur Seite, Schulter des Gegners ziehen.",
      "Schenkel-Pressing → Choke.",
    ],
    commonMistakes: [
      "Zwei Arme in oder zwei Arme out → kein Triangle.",
      "Schlechter Winkel → Gegner stackt durch.",
      "Knie nicht geschlossen → Druck fehlt.",
      "Eigener Kopf nicht zum Knie gezogen — kein Tightness.",
    ],
    usage:
      "Klassische Closed-Guard-Submission. Auch aus offener Guard, von oben, von der Side Control möglich.",
    equipment: ["mat"],
    relatedTechniqueIds: ["bjj_armbar_from_guard", "bjj_closed_guard"],
    disciplines: ["bjj", "mma"],
    trainingArea: ["submissions", "guard"],
    role: "core",
    level: "aufbau",
    alternativeNames: ["Triangle Choke", "Sankaku-Jime", "Dreieck-Würger"],
    coachingCues: [
      "Ein Arm in, ein Arm out — immer zuerst prüfen.",
      "Winkel suchen: Hüfte zur Seite drehen für Choke-Druck.",
      "Kopf zum Knie ziehen — kein aufrechtes Liegen.",
      "Schenkel pressen: Kniekehlendruck auf die Halsschlagader.",
    ],
    safetyNotes: [
      "Sehr effektiver Choke — Partner sofort tippen lassen.",
    ],
    useCases: [
      "Submission wenn Armbar geblockt und ein Arm in Guard bleibt.",
      "Triangle von oben aus Mount oder Side Control.",
      "MMA: Triangle stoppt Punches aus der Guard.",
    ],
    priorityScore: 10,
    frequencyScore: 8,
    diversityGroup: "choke",
    videoSearchQuery: "Triangle choke from guard BJJ tutorial",
  },

  // ─── Neue Techniken ───────────────────────────────────────────────────────
  {
    id: "bjj_scissor_sweep",
    slug: "scissor-sweep",
    name: "Scissor Sweep",
    category: "bjj",
    difficulty: "fortgeschritten",
    description:
      "Der Scissor Sweep ist ein klassischer Guard-Sweep: eine Scheren-Beinbewegung wirft den Gegner auf die Seite. Einstiegspunkt für die Guard-Offensive.",
    steps: [
      "Aus der Closed Guard: Kragen-Griff mit einer Hand, Ärmel-Griff mit der anderen.",
      "Guard öffnen und einen Fuß auf die Hüfte des Gegners.",
      "Anderes Knie kommt auf die Brust des Gegners — fast waagerecht.",
      "Gleichzeitig: Kragen ziehen, Hüftfuß wegdrücken, Brustbein fegt wie eine Schere.",
      "Gegner rollt auf die Seite — sofort in Mount übergehen.",
    ],
    commonMistakes: [
      "Guard ohne Kontrolle öffnen → Gegner passt sofort.",
      "Füße nicht gleichzeitig — Scissor-Bewegung nur halb.",
      "Kragen-Griff loslassen vor dem Sweep.",
      "Nach dem Sweep nicht sofort in Mount übergehen.",
    ],
    usage:
      "Erster Guard-Sweep, den jeder BJJ-Anfänger lernt. Effektiv gegen aufrechte, statische Gegner.",
    equipment: ["mat"],
    relatedTechniqueIds: ["bjj_closed_guard", "bjj_armbar_from_guard"],
    disciplines: ["bjj", "mma"],
    trainingArea: ["sweeps", "guard"],
    role: "core",
    level: "aufbau",
    alternativeNames: ["Scissor Sweep", "Kip Sweep", "Scheren-Sweep"],
    coachingCues: [
      "Beide Griffe vor dem Sweep sichern — kein Griff, kein Sweep.",
      "Scheren-Bewegung: beide Beine gleichzeitig in entgegengesetzte Richtungen.",
      "Körperschwerpunkt mit Kragen-Zug nach unten brechen.",
      "Direkt nach dem Sweep: Mount sichern.",
    ],
    safetyNotes: [],
    useCases: [
      "Gegen Gegner, die sich in der Guard aufrichten.",
      "Sweep-Submission-Kette: Scissor Sweep oder Armbar.",
      "Open Guard → Scissor Sweep als erste Offensive.",
    ],
    priorityScore: 9,
    frequencyScore: 8,
    diversityGroup: "sweep",
    videoSearchQuery: "Scissor sweep BJJ guard tutorial",
  },
  {
    id: "bjj_rear_naked_choke",
    slug: "rear-naked-choke",
    name: "Rear Naked Choke",
    category: "bjj",
    difficulty: "fortgeschritten",
    description:
      "Der bekannteste Würgegriff im Grappling. Von Rücken-Kontrolle aus: Arm um den Hals, andere Hand fixiert — Blutversorgung wird unterbrochen.",
    steps: [
      "Aus der Back Control: Haken (Hooks) mit beiden Beinen.",
      "Schlagarm um den Hals des Gegners — Ellbogen unter dem Kinn.",
      "Handgelenk auf der Halsschlagader, nicht auf der Luftröhre.",
      "Andere Hand fasst den eigenen Bizeps — Kimura-Griff.",
      "Ellbogen zusammendrücken und Schultern zusammenziehen → Choke.",
    ],
    commonMistakes: [
      "Druck auf Luftröhre statt Halsschlagader — schmerzhaft, aber ineffektiv.",
      "Kein Kimura-Griff → Arm kann rausgezogen werden.",
      "Hooks verloren → Gegner dreht sich raus.",
      "Zu weit oben am Hals — Kinn schützt den Hals.",
    ],
    usage:
      "Häufigste Finish-Technik im BJJ und MMA. Aus Back Control extrem schwer zu entkommen.",
    equipment: ["mat"],
    relatedTechniqueIds: ["bjj_triangle_from_guard", "bjj_armbar_from_guard"],
    disciplines: ["bjj", "mma", "wrestling", "self-defense"],
    trainingArea: ["submissions", "ground-control"],
    role: "core",
    level: "aufbau",
    alternativeNames: ["RNC", "Mata Leão", "Sleeper Hold", "Hadaka-Jime"],
    coachingCues: [
      "Ellbogen muss unter dem Kinn sein — Kinn hochdrücken wenn nötig.",
      "Druck auf Halsschlagader, nicht Luftröhre.",
      "Schultern zusammenziehen wie Flügel einfalten.",
      "Hooks behalten — Rückenkontrolle ist die Voraussetzung.",
    ],
    safetyNotes: [
      "Sehr gefährlicher Choke — sofort loslassen wenn Partner tippt.",
      "Im Training nie bis zur Bewusstlosigkeit führen.",
    ],
    useCases: [
      "Finish aus Back Control.",
      "MMA: Übergang von Sprawl → Back Take → RNC.",
      "Self-Defense: effektivste Selbstverteidigungstechnik vom Boden.",
    ],
    priorityScore: 10,
    frequencyScore: 9,
    diversityGroup: "choke",
    videoSearchQuery: "Rear naked choke BJJ tutorial",
  },
  {
    id: "bjj_guillotine_from_guard",
    slug: "guillotine-from-guard",
    name: "Guillotine from Guard",
    category: "bjj",
    difficulty: "fortgeschritten",
    description:
      "Die Guillotine ist ein Armchoke um den Hals des Gegners — von oben oder aus der Guard. Klassische Konter-Submission gegen Takedown-Versuche.",
    steps: [
      "Gegner taucht mit dem Kopf unter → sofort Arm über den Hals legen.",
      "Handgelenk unter das Kinn des Gegners schieben — High Elbow Griff.",
      "Andere Hand fasst das eigene Handgelenk von außen.",
      "Guard schließen, Hüfte nach oben drücken.",
      "Arme zusammenziehen und nach oben heben → Choke.",
    ],
    commonMistakes: [
      "Handgelenk zu tief → auf Luftröhre statt Halsschlagader.",
      "Kein geschlossener Guard → Gegner entkommt nach vorn.",
      "Ellbogen fällt nach außen → Druck fehlt.",
      "Hüfte nicht nach oben → kein Leverage.",
    ],
    usage:
      "Konter gegen Takedowns und Double-Leg-Versuche. Kann stehend oder aus der Guard finalisiert werden.",
    equipment: ["mat"],
    relatedTechniqueIds: ["bjj_closed_guard", "bjj_rear_naked_choke"],
    disciplines: ["bjj", "mma", "wrestling"],
    trainingArea: ["submissions", "guard", "takedown-defense"],
    role: "advanced",
    level: "fortgeschritten",
    alternativeNames: ["Front Choke", "Arm Guillotine", "High Elbow Guillotine"],
    coachingCues: [
      "Handgelenk UNTER das Kinn — nicht auf die Kehle.",
      "High Elbow: Ellbogen zeigt nach oben, nicht zur Seite.",
      "Guard schließen für maximalen Druck.",
      "Hüfte nach oben: Druckpunkt verstärkt den Choke.",
    ],
    safetyNotes: [
      "Guillotine auf Luftröhre ist schmerzhaft — immer Halsschlagader anzielen.",
    ],
    useCases: [
      "Konter gegen Double-Leg oder Single-Leg Takedown.",
      "Aus der Clinch-Position bei gesenktem Kopf des Gegners.",
      "MMA: Guillotine als Takedown-Abwehr aus dem Stand.",
    ],
    priorityScore: 9,
    frequencyScore: 7,
    diversityGroup: "choke",
    videoSearchQuery: "Guillotine choke from guard BJJ tutorial",
  },
];
