import type { Technique } from "../types";

/**
 * Boxing-Techniken — kuratierte Auswahl Anfänger + ausgewählte Fortgeschrittene.
 * Video-/Animation-Slots bleiben absichtlich leer, bis ein rechtssicheres
 * exakt passendes Asset zugeordnet wird (siehe Plan: lieber keins als ein
 * falsches).
 */
export const BOXING_TECHNIQUES: Technique[] = [
  // ─── Anfänger ────────────────────────────────────────────────────────────
  {
    id: "boxing_jab",
    slug: "jab",
    name: "Jab",
    category: "boxing",
    difficulty: "anfaenger",
    description:
      "Der Jab ist der wichtigste Schlag im Boxen — schnell, gerade, mit der Führhand. Setzt Distanz, hält den Gegner beschäftigt und bereitet alle Folgekombinationen vor.",
    steps: [
      "Boxstellung — Schulter linke Seite leicht zum Gegner (für Rechtsausleger).",
      "Hüfte und Schulter rotieren leicht mit, um Reichweite zu gewinnen.",
      "Vorderhand schießt geradlinig nach vorn, Schulter deckt das Kinn.",
      "Faust dreht in den letzten 15 cm 90° nach unten — 'Daumen nach unten' auf Treffermoment.",
      "Hand kommt sofort wieder in Deckung zurück — schneller Rückzug ist Pflicht.",
    ],
    commonMistakes: [
      "Hand wird vor dem Schlag erst gesenkt ('Telegrafieren').",
      "Kinn nicht durch die Schulter gedeckt.",
      "Nach dem Schlag bleibt die Hand draußen — offene Deckung.",
      "Zu viel Hüftrotation — beim Jab nur leicht!",
    ],
    usage:
      "Distanz halten, Gegner antesten, Combos einleiten. Im MMA auch zur Distanz-Kontrolle vor Takedowns.",
    equipment: ["heavy-bag", "pads", "bodyweight"],
    relatedTechniqueIds: ["boxing_cross", "boxing_jab_cross"],
    nextTechniqueId: "boxing_cross",
    disciplines: ["boxing", "kickboxen", "muay-thai", "mma", "fitness-kickboxen"],
    trainingArea: ["punches", "stand-up"],
    role: "core",
    level: "anfaenger",
    alternativeNames: ["Führhand-Gerade", "Straight Lead"],
    coachingCues: [
      "Schulter deckt das Kinn beim Schlag.",
      "Rückzug genauso schnell wie der Schlag — nicht warten.",
      "Kein Telegrafen: Hand startet direkt aus der Deckung.",
      "Nur leichter Hüfteinsatz — kein Ausdrehen.",
    ],
    safetyNotes: [
      "Handgelenk muss beim Aufprall gerade sein — kein Knicken.",
    ],
    useCases: [
      "Distanz halten gegen Druckgegner.",
      "Eröffnen von Jab-Cross-Kombinationen.",
      "Gegner zur Reaktion zwingen, um seine Deckung zu lesen.",
    ],
    priorityScore: 10,
    frequencyScore: 10,
    diversityGroup: "straight-punch",
    videoSearchQuery: "Jab boxing technique tutorial",
  },
  {
    id: "boxing_cross",
    slug: "cross",
    name: "Cross",
    category: "boxing",
    difficulty: "anfaenger",
    description:
      "Der Cross ist der gerade Schlag mit der Schlaghand. Mehr Power als der Jab, weil die Hüfte voll mitrotiert.",
    steps: [
      "Aus der Boxstellung Hüfte und Schulter explosiv rotieren.",
      "Hinterer Fuß dreht — Ferse hebt sich, Knie zeigt zur Mitte.",
      "Schlaghand schießt geradlinig zur Mitte des Ziels.",
      "Faust dreht im Kontaktmoment 90° (Daumen nach unten).",
      "Sofort zurück in Deckung — Schulter deckt das Kinn.",
    ],
    commonMistakes: [
      "Kein Hüftdreh — Schlag kommt nur aus dem Arm.",
      "Hinterer Fuß bleibt flach — keine Power.",
      "Vorderhand sinkt während des Crosses — Konter-Hook möglich.",
      "Nach dem Schlag steht der Boxer 'offen' da.",
    ],
    usage:
      "Schwerer Folge-Schlag nach Jab. Im 1-2 die schmerzhafte Hand. Auch als Konter gegen einen kommenden Gegner stark.",
    equipment: ["heavy-bag", "pads", "bodyweight"],
    relatedTechniqueIds: ["boxing_jab", "boxing_jab_cross"],
    nextTechniqueId: "boxing_hook",
    disciplines: ["boxing", "kickboxen", "muay-thai", "mma", "fitness-kickboxen"],
    trainingArea: ["punches", "stand-up"],
    role: "core",
    level: "anfaenger",
    alternativeNames: ["Gerade Rechts", "Straight Right", "Power Hand"],
    coachingCues: [
      "Hintere Ferse dreht hoch — ohne diese Bewegung kein Hüftdreh.",
      "Geradlinig zum Ziel, kein Bogen.",
      "Vorderhand bleibt oben während des Crosses.",
      "Rückzug genauso schnell wie der Vortrieb.",
    ],
    safetyNotes: [
      "Nicht zu weit vorbeugen — Überstreckung des Rückens bei starkem Hüftdreh vermeiden.",
    ],
    useCases: [
      "Power-Schlag nach dem aufbauenden Jab.",
      "Konter gegen reinkommende Gegner.",
      "Beenden von Kombinationen mit maximaler Kraft.",
    ],
    priorityScore: 10,
    frequencyScore: 9,
    diversityGroup: "straight-punch",
    videoSearchQuery: "Cross boxing technique tutorial",
  },
  {
    id: "boxing_hook",
    slug: "hook",
    name: "Hook",
    category: "boxing",
    difficulty: "anfaenger",
    description:
      "Der Hook ist ein seitlicher Halbkreis-Schlag — meistens mit der Führhand zum Kopf oder Körper. Kommt aus dem Toten Winkel.",
    steps: [
      "Ellbogen waagerecht auf Schulterhöhe heben.",
      "Faust auf Höhe des Ellbogens, Daumen zeigt nach oben (Vertical Hook) oder zur Mitte (Horizontal Hook).",
      "Hüfte und Vorderfuß rotieren explosiv in Schlagrichtung.",
      "Schlag entsteht durch Hüftdrehung, nicht durch Armschwingen.",
      "Nach dem Schlag sofort Deckung — Hook lässt einen offen.",
    ],
    commonMistakes: [
      "Ellbogen zu tief → wird zum 'Schwinger'.",
      "Kein Hüftdreh → Schlag aus dem Arm = keine Power.",
      "Andere Hand sinkt während des Hooks ab.",
      "Zu großer Bogen → Gegner sieht ihn kommen.",
    ],
    usage:
      "Nach Jab-Cross die klassische 1-2-3-Combo. Auch als Konter gegen einen reinkommenden Gegner.",
    equipment: ["heavy-bag", "pads", "bodyweight"],
    relatedTechniqueIds: ["boxing_uppercut", "boxing_jab_cross_hook"],
    nextTechniqueId: "boxing_uppercut",
    disciplines: ["boxing", "kickboxen", "muay-thai", "mma", "fitness-kickboxen"],
    trainingArea: ["punches", "stand-up"],
    role: "core",
    level: "anfaenger",
    alternativeNames: ["Haken", "Left Hook", "Short Hook"],
    coachingCues: [
      "Ellbogen auf Schulterhöhe — nicht drüber, nicht drunter.",
      "Hüfte dreht: Kraft kommt vom Boden, nicht vom Arm.",
      "Kein Schwingen — kompakter, kurzer Schlag.",
      "Sofort zurück, Deckung halten.",
    ],
    safetyNotes: [
      "Ellbogen zu hoch kann die Schulter belasten — auf Schulterhöhe halten.",
    ],
    useCases: [
      "Dritter Schlag in der 1-2-3-Kombination.",
      "Konter aus dem Slip oder Roll.",
      "Body-Hook zum Aushöhlen des Gegners.",
    ],
    priorityScore: 9,
    frequencyScore: 9,
    diversityGroup: "hook",
    videoSearchQuery: "Boxing Hook technique tutorial",
  },
  {
    id: "boxing_uppercut",
    slug: "uppercut",
    name: "Uppercut",
    category: "boxing",
    difficulty: "anfaenger",
    description:
      "Der Uppercut ist ein Schlag von unten nach oben — Knock-Out-Schlag aus der Nahdistanz, ideal gegen vorbeugende Gegner.",
    steps: [
      "Knie leicht beugen — die Power kommt von unten.",
      "Faust seitlich am Körper, Handfläche nach innen.",
      "Beine, Hüfte und Schulter explosiv strecken/rotieren.",
      "Faust schießt diagonal nach oben zur Mitte des Ziels (Kinn oder Solar plexus).",
      "Sofort zurück in Deckung — Uppercut öffnet die Mitte.",
    ],
    commonMistakes: [
      "Schlag kommt nur aus dem Arm, nicht aus den Beinen.",
      "Zu großer Holpunkt — Gegner sieht es kommen.",
      "Hand zu weit nach unten geholt → andere Hand sinkt ab.",
      "Auf Distanz gespielt — Uppercut ist ein Nahdistanz-Schlag.",
    ],
    usage:
      "Gegen Gegner, die sich zur Mitte einkrümmen. Body-Uppercut zermürbt, Kopf-Uppercut endet Kämpfe.",
    equipment: ["heavy-bag", "pads", "bodyweight"],
    relatedTechniqueIds: ["boxing_hook"],
    nextTechniqueId: "boxing_jab_cross_hook",
    disciplines: ["boxing", "kickboxen", "muay-thai", "mma", "fitness-kickboxen"],
    trainingArea: ["punches", "stand-up"],
    role: "core",
    level: "anfaenger",
    alternativeNames: ["Aufwärtshaken", "Short Uppercut"],
    coachingCues: [
      "Knie beugen — Power kommt aus der Aufwärtsbewegung der Beine.",
      "Nicht zu weit ausholen — kleiner, explosiver Dip.",
      "Kontaktfläche: Vorderseite der Faust auf dem Kinn.",
      "Nur in Nahdistanz — bei zu großer Entfernung kommt nichts an.",
    ],
    safetyNotes: [
      "Nicht das Handgelenk überstrecken — Aufprall mit gerader Faust.",
    ],
    useCases: [
      "Nach Inside-Slip gegen einen Jab als Konter-Uppercut.",
      "Aus dem Clinch oder der Nahdistanz.",
      "Body-Uppercut zur Leber als Combo-Abschluss.",
    ],
    priorityScore: 8,
    frequencyScore: 7,
    diversityGroup: "uppercut",
    videoSearchQuery: "Uppercut boxing technique tutorial",
  },
  {
    id: "boxing_guard",
    slug: "guard",
    name: "Guard / Deckung",
    category: "boxing",
    difficulty: "anfaenger",
    description:
      "Die Deckung ist das Fundament jeder Verteidigung. Hände schützen das Kinn, Ellbogen schützen Rippen und Leber.",
    steps: [
      "Hände auf Höhe der Wangen, Daumen nach innen.",
      "Ellbogen eng am Körper, schützen Leber und Rippen.",
      "Kinn leicht eingezogen, Blick über die Fäuste hinweg.",
      "Schultern locker, nicht hochgezogen.",
      "Atmung gleichmäßig — Anspannung kostet Ausdauer.",
    ],
    commonMistakes: [
      "Kinn zu hoch → leichtes Ziel.",
      "Ellbogen abstehend → Body-Shots gehen durch.",
      "Hände zu weit weg vom Kopf → Reaktionszeit zu lang.",
      "Schultern hochgezogen → schnelle Ermüdung.",
    ],
    usage:
      "Grundzustand zwischen Aktionen. Aus der Deckung werden alle Schläge und Verteidigungen geschossen.",
    equipment: ["bodyweight"],
    relatedTechniqueIds: ["boxing_footwork", "boxing_slip"],
    disciplines: ["boxing", "kickboxen", "muay-thai", "mma", "fitness-kickboxen"],
    trainingArea: ["defense", "stand-up"],
    role: "core",
    level: "anfaenger",
    alternativeNames: ["Box Guard", "Deckung", "High Guard"],
    coachingCues: [
      "Hände auf Wangenhöhe — nicht auf Brusthöhe.",
      "Ellbogen eng: ein Blatt Papier sollte kaum zwischen Ellbogen und Rumpf passen.",
      "Kinn runter, Blick geht über die Fäuste — nicht darunter durch.",
      "Schultern locker lassen, nicht hochziehen.",
    ],
    safetyNotes: [
      "Auf korrekten Handgelenkwinkel achten — Bandagen und Handschuhe sind Pflicht beim Schlagbetrieb.",
    ],
    useCases: [
      "Ausgangspunkt für alle Angriffe und Defensivbewegungen.",
      "Auffangen von Gegner-Schlägen (Shell-Deckung).",
      "Erholung im Austausch ohne zurückzutreten.",
    ],
    priorityScore: 10,
    frequencyScore: 10,
    diversityGroup: "defensive",
    videoSearchQuery: "Boxing guard stance tutorial",
  },
  {
    id: "boxing_footwork",
    slug: "footwork",
    name: "Footwork",
    category: "boxing",
    difficulty: "anfaenger",
    description:
      "Bewegung im Boxring entscheidet alles. Stride, Pivot, Side-Step — Boxer arbeitet immer aus Bewegung.",
    steps: [
      "Schultergurt-breite Stellung, Vorderfuß zum Gegner.",
      "Kleine, gleitende Schritte — niemals Beine kreuzen.",
      "Schritte starten immer mit dem näheren Fuß zur Bewegungsrichtung.",
      "Knie weich, Gewicht auf den Fußballen.",
      "Pivot: Vorderfuß bleibt, Hinterfuß dreht zur Seite.",
    ],
    commonMistakes: [
      "Beine werden gekreuzt → Sturzgefahr beim Treffer.",
      "Zu weite Schritte → Balance weg.",
      "Auf den Fersen → langsame Reaktion.",
      "Statisch gegen einen beweglichen Gegner.",
    ],
    usage:
      "Distanz aufbauen, Winkel öffnen, aus Druckzonen rauskommen. Footwork unterscheidet den Boxer vom Schläger.",
    equipment: ["bodyweight", "jump-rope"],
    relatedTechniqueIds: ["boxing_guard", "boxing_jab"],
    disciplines: ["boxing", "kickboxen", "muay-thai", "mma", "fitness-kickboxen"],
    trainingArea: ["footwork", "stand-up"],
    role: "core",
    level: "anfaenger",
    alternativeNames: ["Ring-Bewegung", "Stance & Motion"],
    coachingCues: [
      "Immer führender Fuß zuerst in Laufrichtung — Beine nie kreuzen.",
      "Auf den Fußballen bleiben — nicht auf den Fersen.",
      "Kleine, kontrollierte Schritte: Distanzkontrolle ist wichtiger als Geschwindigkeit.",
      "Pivot: Vorderfuß dreht, Hinterfuß kommt nach.",
    ],
    safetyNotes: [],
    useCases: [
      "Distanz gegen Druckgegner aufrechterhalten.",
      "Winkel öffnen für Angriffe aus dem blinden Winkel.",
      "Aus einer Ecke oder Druckzone entkommen.",
    ],
    priorityScore: 9,
    frequencyScore: 9,
    diversityGroup: "footwork",
    videoSearchQuery: "Boxing footwork basics tutorial",
  },
  {
    id: "boxing_slip",
    slug: "slip",
    name: "Slip",
    category: "boxing",
    difficulty: "anfaenger",
    description:
      "Slip ist eine Kopfbewegung zur Seite, mit der man Geraden Schlägen ausweicht — ohne die Schlaghand wegzunehmen.",
    steps: [
      "Aus der Boxstellung leichter Knickschlag mit dem Knie.",
      "Oberkörper neigt sich seitlich (nicht nach hinten!).",
      "Kopf schiebt sich aus der Schlaglinie — entweder nach links (gegen Cross) oder rechts (gegen Jab).",
      "Hände bleiben in Deckung, Augen am Gegner.",
      "Sofort wieder in Mittelstellung — fertig zum Konter.",
    ],
    commonMistakes: [
      "Nach hinten ausweichen → Distanz verloren, kein Konter möglich.",
      "Kopf zu tief → schwer wieder hochzukommen.",
      "Augen geschlossen → nichts mehr gesehen.",
      "Slip zu früh → Gegner nutzt es als Feint.",
    ],
    usage:
      "Verteidigung gegen Geradeschläge. Setzt den Boxer gleichzeitig in eine perfekte Konter-Position.",
    equipment: ["bodyweight", "pads"],
    relatedTechniqueIds: ["boxing_roll", "boxing_counter_cross"],
    nextTechniqueId: "boxing_roll",
    disciplines: ["boxing", "kickboxen", "muay-thai", "mma", "fitness-kickboxen"],
    trainingArea: ["defense", "stand-up"],
    role: "core",
    level: "anfaenger",
    alternativeNames: ["Ausweichen", "Head Movement"],
    coachingCues: [
      "Körper neigt sich seitlich, nicht nach hinten — Knie führen die Bewegung.",
      "Hände IMMER oben — kein Absenken beim Slip.",
      "Augen am Gegner — Kopfbewegung ist defensiv, kein Augen-zu-Reflex.",
      "Aus dem Slip sofort Konter setzen — nicht warten.",
    ],
    safetyNotes: [
      "Zu tiefes Abtauchen öffnet den Hinterkopf für Uppercuts.",
    ],
    useCases: [
      "Jab slippt nach außen — Konter-Cross.",
      "Cross slippt innen — Konter-Hook.",
      "Distanzkontrolle: keinen Schaden nehmen und gleichzeitig nahe bleiben.",
    ],
    priorityScore: 8,
    frequencyScore: 8,
    diversityGroup: "defensive",
    videoSearchQuery: "Boxing slip head movement tutorial",
  },
  {
    id: "boxing_roll",
    slug: "roll",
    name: "Roll",
    category: "boxing",
    difficulty: "anfaenger",
    description:
      "Der Roll ist eine Halbkreis-Bewegung des Oberkörpers, um Hooks zu vermeiden. Klassische Verteidigung gegen seitliche Schläge.",
    steps: [
      "Knie beugen, Oberkörper bewegt sich in einer 'U'-Form.",
      "Auf der Schlagseite des Gegners abtauchen.",
      "Halbkreis durch die Schlaglinie unter dem Hook hindurch.",
      "Auf der anderen Seite wieder hochkommen — Hände bleiben oben.",
      "Aus der Roll-Endposition direkt kontern (Hook oder Cross).",
    ],
    commonMistakes: [
      "Tiefes Abtauchen statt Halbkreis → langsame Rückkehr.",
      "Kein Knie-Knick → Roll wird flach.",
      "Hände sinken während des Rollens.",
      "Augen weg vom Gegner.",
    ],
    usage:
      "Klassische Verteidigung gegen Hooks. Endposition ist ideal für Konter.",
    equipment: ["bodyweight", "pads"],
    relatedTechniqueIds: ["boxing_slip"],
    disciplines: ["boxing", "kickboxen", "mma", "fitness-kickboxen"],
    trainingArea: ["defense", "stand-up"],
    role: "support",
    level: "aufbau",
    alternativeNames: ["Duck", "Bob and Weave", "Abtauchen"],
    coachingCues: [
      "U-Form: runter, durch, hoch — kein einfaches Abtauchen.",
      "Knie leiten die Bewegung — nicht die Schultern.",
      "Hände IMMER in Deckung beim Durchrollen.",
      "Direkt aus der Roll-Endposition angreifen.",
    ],
    safetyNotes: [
      "Nicht zu weit unter den Hook abtauchen — Gegner kann Knie oder Uppercut einsetzen.",
    ],
    useCases: [
      "Gegen Lead-Hook verteidigen und Konter-Cross setzen.",
      "Gegen Power-Hook von einem druckgebenden Gegner.",
      "Aus der Enge: Raum schaffen durch das Unterqueren.",
    ],
    priorityScore: 7,
    frequencyScore: 7,
    diversityGroup: "defensive",
    videoSearchQuery: "Boxing roll bob weave tutorial",
  },

  // ─── Fortgeschritten ─────────────────────────────────────────────────────
  {
    id: "boxing_jab_cross",
    slug: "jab-cross",
    name: "Jab-Cross (1-2)",
    category: "boxing",
    difficulty: "fortgeschritten",
    description:
      "Die fundamentalste Combo im Boxen. Der Jab öffnet, der Cross trifft. Beidhändig, schnell, präzise.",
    steps: [
      "Jab: schnell, geradlinig, Hand auf Augenhöhe.",
      "Sofort danach Cross — keine Pause zwischen den Schlägen.",
      "Hüfte rotiert mit dem Cross voll mit.",
      "Beide Hände kehren sofort in Deckung zurück.",
      "Optional: Halben Schritt nach vorn, um Distanz zu schließen.",
    ],
    commonMistakes: [
      "Jab und Cross werden mit Pause geschlagen — verliert Tempo.",
      "Cross verlangsamt durch Vorbereitung.",
      "Vorderhand sinkt nach dem Jab.",
      "Hüftdreh fehlt beim Cross.",
    ],
    usage:
      "Erste Combo, die jeder lernt. Universell einsetzbar — am Sandsack, auf Pads, im Sparring.",
    equipment: ["heavy-bag", "pads"],
    techniqueIds: ["boxing_jab", "boxing_cross"],
    relatedTechniqueIds: ["boxing_jab_cross_hook", "boxing_jab", "boxing_cross"],
    nextTechniqueId: "boxing_jab_cross_hook",
    disciplines: ["boxing", "kickboxen", "muay-thai", "mma", "fitness-kickboxen"],
    trainingArea: ["combos", "punches"],
    role: "combo",
    level: "aufbau",
    alternativeNames: ["1-2", "One-Two", "Straight Combo"],
    coachingCues: [
      "Kein Reset zwischen Jab und Cross — fließender Übergang.",
      "Cross-Hüfte dreht in dieselbe Bewegung des Jab-Rückzugs.",
      "Beide Hände gleichzeitig zurück nach dem Cross.",
      "Halber Schritt nach vorn beim Jab erhöht die Cross-Distanz.",
    ],
    safetyNotes: [],
    useCases: [
      "Eröffnen aller Boxing-Kombinationen.",
      "Konter gegen reinkommende Gegner.",
      "Distanz schließen und sofort wieder öffnen.",
    ],
    priorityScore: 10,
    frequencyScore: 10,
    diversityGroup: "combo",
    videoSearchQuery: "Jab Cross 1-2 boxing combination tutorial",
  },
  {
    id: "boxing_jab_cross_hook",
    slug: "jab-cross-hook",
    name: "Jab-Cross-Hook (1-2-3)",
    category: "boxing",
    difficulty: "fortgeschritten",
    description:
      "Die klassische 3-Schlag-Kombo: Jab öffnet, Cross trifft mittig, Hook landet im Toten Winkel.",
    steps: [
      "1: Jab — schnell, scharf.",
      "2: Cross — mit Hüftdreh, voller Power.",
      "3: Hook — kommt vom Cross-Rückzug, mit Vorderhand.",
      "Hüfte rotiert dabei zweimal: einmal in Cross-Richtung, einmal zurück für den Hook.",
      "Nach dem Hook: sofort wieder in Deckung oder Pivot zur Seite.",
    ],
    commonMistakes: [
      "Hook ohne Hüftrotation — schlägt aus dem Arm.",
      "Pause zwischen Schlag 2 und 3.",
      "Cross-Hand fällt vor dem Hook ab.",
      "Boxer steht nach Hook offen — kein Pivot.",
    ],
    usage:
      "Nach dem 1-2 lernt jeder Boxer das 1-2-3. Setup für Body-Shots oder Übergang in Defensive.",
    equipment: ["heavy-bag", "pads"],
    techniqueIds: ["boxing_jab", "boxing_cross", "boxing_hook"],
    relatedTechniqueIds: ["boxing_jab_cross"],
    disciplines: ["boxing", "kickboxen", "muay-thai", "mma", "fitness-kickboxen"],
    trainingArea: ["combos", "punches"],
    role: "combo",
    level: "aufbau",
    alternativeNames: ["1-2-3", "One-Two-Three", "Triple Combo"],
    coachingCues: [
      "Hook fließt aus dem Cross-Rückzug — keine Pause.",
      "Hüfte dreht beim Cross nach rechts, beim Hook wieder nach links.",
      "Cross-Hand bleibt am Kinn bis der Hook zurück ist.",
      "Pivot nach dem Hook schließt die offene Position.",
    ],
    safetyNotes: [],
    useCases: [
      "Standardkombination im Training und Sparring.",
      "Setup für Body-Hook nach dem Kopf-Angriff.",
      "Druck aufbauen mit dreifacher Angriffsstaffelung.",
    ],
    priorityScore: 9,
    frequencyScore: 9,
    diversityGroup: "combo",
    videoSearchQuery: "Jab Cross Hook 1-2-3 boxing combination tutorial",
  },

  // ─── Neue Techniken ───────────────────────────────────────────────────────
  {
    id: "boxing_body_hook",
    slug: "body-hook",
    name: "Body Hook",
    category: "boxing",
    difficulty: "fortgeschritten",
    description:
      "Der Body Hook zielt auf Leber oder Rippen des Gegners. Ein präziser Körperschlag zermürbt die Ausdauer und erzwingt das Absenken der Deckung.",
    steps: [
      "Aus der Boxstellung leicht in die Knie gehen — Level ändern.",
      "Ellbogen auf Körperhöhe, Schlag kommt waagerecht.",
      "Hüfte explosiv zur Schlagseite drehen.",
      "Treffer auf die Leber (rechte Seite des Gegners) oder die Rippen.",
      "Sofort Kopf aus der Mitte nehmen — hoch oder zur Seite.",
    ],
    commonMistakes: [
      "Kein Level Change — Schlag trifft Ellbogen des Gegners.",
      "Hüftdreh fehlt → kein Gewicht hinter dem Schlag.",
      "Nach dem Body-Hook Kopf in der Mitte lassen → Konter.",
      "Zu weit ausholen → Gegner sieht es und geht tief.",
    ],
    usage:
      "Zermürbt das Mittelteil, erzwingt das Senken der Deckung für Kopfschläge. Die Leber ist das begehrteste Ziel.",
    equipment: ["heavy-bag", "pads", "bodyweight"],
    relatedTechniqueIds: ["boxing_hook", "boxing_uppercut"],
    disciplines: ["boxing", "kickboxen", "mma", "fitness-kickboxen"],
    trainingArea: ["punches", "stand-up"],
    role: "advanced",
    level: "fortgeschritten",
    alternativeNames: ["Liver Shot", "Körperhaken", "Body Shot"],
    coachingCues: [
      "Level-Change: Knie beugen, nicht Rücken beugen.",
      "Kompakter, kurzer Schwung — kein Roundhouse-Arm.",
      "Kontaktstelle: untere Knöchel-Reihe der Faust.",
      "Kopf sofort raus nach dem Treffer.",
    ],
    safetyNotes: [
      "Im Sparring: vorher klären, ob Body-Shots erlaubt sind.",
    ],
    useCases: [
      "Level-wechselnde Kombination: Körper-Körper-Kopf.",
      "Leber-Shot als Kampf-ender Schlag.",
      "Erzwingen des Armabsenkens für Kopf-Uppercut.",
    ],
    priorityScore: 8,
    frequencyScore: 7,
    diversityGroup: "hook",
    videoSearchQuery: "Body Hook liver shot boxing tutorial",
  },
  {
    id: "boxing_overhand",
    slug: "overhand",
    name: "Overhand",
    category: "boxing",
    difficulty: "fortgeschritten",
    description:
      "Der Overhand ist ein bogenförmiger Power-Schlag von oben über die Deckung des Gegners. Ideal gegen kleinere Gegner oder solche, die sich vorbeugen.",
    steps: [
      "Aus der Deckung: Schlaghand zieht leicht nach außen und hinten.",
      "Faust fährt in einem weiten Bogen nach oben und dann nach vorne-unten.",
      "Hüfte und Schulter rotieren voll mit.",
      "Treffer auf die Schläfe oder Kinn des Gegners — kommt von oben.",
      "Sofort Deckung zurück — Overhand lässt den Kopf offen.",
    ],
    commonMistakes: [
      "Zu viel Telegrafieren durch das Herausziehen der Hand.",
      "Kein Hüftdreh → nur ein Armschwung.",
      "Auf Distanz geworfen, wo er zu langsam ankommt.",
      "Nach dem Schlag kein Rückzug in die Deckung.",
    ],
    usage:
      "Über die Deckung eines geduckt schlagenden Gegners. Klassischer Konter gegen Jabs oder auf Distanz.",
    equipment: ["heavy-bag", "pads", "bodyweight"],
    relatedTechniqueIds: ["boxing_cross", "boxing_hook"],
    disciplines: ["boxing", "kickboxen", "mma"],
    trainingArea: ["punches", "stand-up"],
    role: "advanced",
    level: "fortgeschritten",
    alternativeNames: ["Roundhouse Right", "Bolo Punch", "Power Right"],
    coachingCues: [
      "Bogen von außen-oben nach innen-unten — nicht wie ein Cross.",
      "Hüfte dreht wie beim Cross — maximaler Einsatz.",
      "Gegen Gegner, die die Deckung hochziehen: Overhand geht drüber.",
      "Setup: Jab oder Feint vorher, damit Gegner reagiert.",
    ],
    safetyNotes: [
      "Handgelenk gerade beim Aufprall halten — schräger Winkel erhöht Verletzungsrisiko.",
    ],
    useCases: [
      "Konter auf Jab: Over-the-top Power-Schlag.",
      "Gegen kleinere Gegner oder Gegner, die sich vorbeugen.",
      "Eröffner eines bogenförmigen Angriffs als Surprise-Technik.",
    ],
    priorityScore: 7,
    frequencyScore: 6,
    diversityGroup: "straight-punch",
    videoSearchQuery: "Overhand boxing punch tutorial",
  },
  {
    id: "boxing_double_jab",
    slug: "double-jab",
    name: "Double Jab",
    category: "boxing",
    difficulty: "fortgeschritten",
    description:
      "Zwei schnelle Jabs hintereinander — der erste zum Distanz messen, der zweite mit mehr Körpereinsatz. Verwirrt die Deckung und bereitet Power-Schläge vor.",
    steps: [
      "Erster Jab: Messjab — schnell, wenig Körpereinsatz.",
      "Hand sofort zurück — aber nicht ganz in Deckung.",
      "Zweiter Jab: mit leichtem Vorwärtsschritt und mehr Schulter.",
      "Cross direkt anschließen ohne Pause.",
      "Deckung nach dem Doppel-Jab sofort wieder schließen.",
    ],
    commonMistakes: [
      "Beide Jabs identisch: kein Überraschungseffekt.",
      "Zweiter Jab zu langsam — Gegner reagiert zwischen den Schlägen.",
      "Vorderhand nach dem zweiten Jab offen gelassen.",
      "Ohne Cross-Abschluss — Potenzial verschenkt.",
    ],
    usage:
      "Distanz messen, Rhythmus brechen, Deckung des Gegners öffnen. Der zweite Jab dient oft als versteckter Einleiter zum Cross.",
    equipment: ["heavy-bag", "pads", "bodyweight"],
    relatedTechniqueIds: ["boxing_jab", "boxing_jab_cross"],
    disciplines: ["boxing", "kickboxen", "muay-thai", "mma", "fitness-kickboxen"],
    trainingArea: ["punches", "combos"],
    role: "advanced",
    level: "fortgeschritten",
    alternativeNames: ["Double-Jab", "1-1", "Stutter Jab"],
    coachingCues: [
      "Erster Jab: leicht, schnell — zweiter mit Schritt.",
      "Kein Rhythmus — der zweite Jab muss überraschend kommen.",
      "Beide Jabs aus der Deckung, keine Ausholbewegung.",
      "Direkt mit Cross oder Hook abschließen.",
    ],
    safetyNotes: [],
    useCases: [
      "Rhythmusbrechend gegen reaktive Gegner.",
      "Zwei-Jab-Cross als längere Eröffnungskombo.",
      "Testen der Deckung auf beiden Seiten vor dem Finalschlag.",
    ],
    priorityScore: 7,
    frequencyScore: 7,
    diversityGroup: "straight-punch",
    videoSearchQuery: "Double jab boxing technique tutorial",
  },
  {
    id: "boxing_counter_cross",
    slug: "counter-cross",
    name: "Counter Cross",
    category: "boxing",
    difficulty: "fortgeschritten",
    description:
      "Der Counter Cross kommt direkt nach einem gegnerischen Jab — beim Slip nach innen schießt die eigene Schlaghand nach vorn. Timing schlägt Power.",
    steps: [
      "Slip nach außen gegen den gegnerischen Jab (nach rechts für Rechtsausleger).",
      "Im selben Moment Cross schießen — Timing ist alles.",
      "Hüfte dreht voll mit — Konter mit vollem Gewicht.",
      "Treffer auf Kinn oder Schläfe des Gegners, dessen Arm noch ausgestreckt ist.",
      "Sofort Deckung — in dieser Position ist man für einen Bruchteil offen.",
    ],
    commonMistakes: [
      "Zu spät: erst slippt man, dann schlägt man — Moment ist vorbei.",
      "Cross zu langsam durch Zögern.",
      "Kein Slip — reiner Counter ohne Schutz.",
      "Nach dem Counter stehen bleiben.",
    ],
    usage:
      "Einer der wirkungsvollsten Konter im Boxen. Der Gegner bewegt seinen Kopf in den Cross. Timing-Technik für Fortgeschrittene.",
    equipment: ["pads", "bodyweight"],
    relatedTechniqueIds: ["boxing_slip", "boxing_cross"],
    disciplines: ["boxing", "kickboxen", "muay-thai", "mma"],
    trainingArea: ["punches", "defense"],
    role: "advanced",
    level: "fortgeschritten",
    alternativeNames: ["Slip-Cross", "Inside Counter", "Gegenschlag"],
    coachingCues: [
      "Slip und Cross sind EINE Bewegung — nicht zwei nacheinander.",
      "Den Slip nicht übertreiben — nur soweit wie nötig.",
      "Cross trifft, während der Arm des Gegners noch ausgestreckt ist.",
      "Danach Schritt zur Seite oder zurück — nicht geradeaus.",
    ],
    safetyNotes: [
      "Timing-Training nur mit erfahrenem Partner oder Pad-Holder.",
    ],
    useCases: [
      "Konter auf einen klassischen Jab-Eröffner.",
      "Reaktionstechnik nach dem Slip gegen Geraden.",
      "Distanzkontrolle: Gegner wird bestraft, wenn er schlägt.",
    ],
    priorityScore: 8,
    frequencyScore: 6,
    diversityGroup: "straight-punch",
    videoSearchQuery: "Counter cross boxing slip counter tutorial",
  },
];
