import type { Technique } from "../types";

/**
 * Kickboxen-Techniken — Kickboxen-spezifische Techniken, die nicht bereits
 * in Boxing oder Muay Thai abgedeckt sind. Fokus auf klassische und Sport-
 * Kickboxen-Techniken (europäisch/amerikanisch).
 */
export const KICKBOXEN_TECHNIQUES: Technique[] = [
  {
    id: "kb_high_kick",
    slug: "high-kick",
    name: "High Kick",
    category: "boxing",
    difficulty: "fortgeschritten",
    description:
      "Der High Kick zielt auf Kopf oder Schläfe des Gegners — einer der spektakulärsten und gefährlichsten Kicks im Kickboxen. Erfordert hohe Flexibilität und präzises Timing.",
    steps: [
      "Standfuß dreht 90° nach außen — volle Hüftmobilität aktivieren.",
      "Schlagbein kommt mit voller Hüftrotation im Bogen nach oben.",
      "Kontakt: Spann oder Schienbein auf Schläfe oder Kinn.",
      "Oberkörper rotiert konträr, Hände bleiben in Deckung.",
      "Bein zurück in Deckung — kein Stehen nach dem Kick.",
    ],
    commonMistakes: [
      "Zu wenig Flexibilität → Kick bleibt auf mittlerem Niveau.",
      "Standfuß dreht nicht → Hüftblockade, schwacher Kick.",
      "Hände sinken während des Kicks.",
      "Gleichgewicht nach dem Kick verloren.",
    ],
    usage:
      "KO-Technik für Wettkampf und Fortgeschrittenen-Sparring. Erfordert kontinuierliches Dehntraining.",
    equipment: ["heavy-bag", "pads", "bodyweight"],
    relatedTechniqueIds: [],
    disciplines: ["kickboxen", "muay-thai", "karate", "fitness-kickboxen"],
    trainingArea: ["kicks", "stand-up"],
    role: "advanced",
    level: "fortgeschritten",
    alternativeNames: ["Head Kick", "Kopfkick", "Jodan Mawashi Geri"],
    coachingCues: [
      "Tägliches Dehntraining ist Pflicht für echte High Kicks.",
      "Standfuß 90° — keine halbe Drehung.",
      "Kick kommt von der Seite, nicht von vorn.",
      "Hände OBEN: Head Kick öffnet den eigenen Kopf für Konter.",
    ],
    safetyNotes: [
      "Ohne ausreichende Hüftflexibilität Muskelzerrung möglich.",
      "Im Sparring: High Kicks immer mit Kontrollmindestabstand.",
    ],
    useCases: [
      "KO-Finish im Wettkampf.",
      "Combo-Abschluss: Jab-Cross-High Kick.",
      "Überraschungstechnik nach Low-Kick-Setup.",
    ],
    priorityScore: 8,
    frequencyScore: 6,
    diversityGroup: "roundhouse",
    videoSearchQuery: "High kick kickboxing head kick technique tutorial",
  },
  {
    id: "kb_side_kick",
    slug: "side-kick",
    name: "Side Kick",
    category: "boxing",
    difficulty: "fortgeschritten",
    description:
      "Der Side Kick ist ein linearer Tritt zur Seite — Kraft durch Körperextension. Im Kickboxen und Karate eine der mächtigsten Einzeltechniken.",
    steps: [
      "Aus dem Stand: Körper dreht 90° zur Seite des Schlagbeins.",
      "Knie des Schlagbeins zur Brust anziehen.",
      "Ferse explosiv nach vorn schießen — Bein streckt sich vollständig.",
      "Hüfte dreht nach vorn für maximale Extension.",
      "Kontaktfläche: Ferse oder Außenkante des Fußes.",
    ],
    commonMistakes: [
      "Ferse nicht als Kontaktfläche — schlägt mit dem Spann.",
      "Kein Körperdreh → kein Hebel, schwacher Kick.",
      "Hüfte bleibt zurück — kein Drive nach vorn.",
      "Knie nicht hoch genug angezogen vor dem Schuss.",
    ],
    usage:
      "Distanzkick mit enormer Stoppkraft. Hält Gegner auf Abstand und kann ihn rückwärts schleudern.",
    equipment: ["heavy-bag", "pads", "bodyweight"],
    relatedTechniqueIds: [],
    disciplines: ["kickboxen", "karate", "self-defense", "fitness-kickboxen"],
    trainingArea: ["kicks", "stand-up"],
    role: "advanced",
    level: "fortgeschritten",
    alternativeNames: ["Yoko Geri", "Seitwärtskick", "Side Thrust Kick"],
    coachingCues: [
      "Körper dreht komplett zur Seite — Schulter zeigt zum Ziel.",
      "Knie zuerst hochziehen, dann Ferse schießen.",
      "Ferse als Kontaktfläche: Zehe nach unten zeigen beim Kick.",
      "Hüfte rotiert nach vorn für maximale Extension.",
    ],
    safetyNotes: [
      "Knie-Extension nur bis zur vollen Streckung — nicht überstrecken.",
    ],
    useCases: [
      "Distanz-Kick mit Stoppkraft gegen reinkommende Gegner.",
      "Combo-Element im Wechsel mit Roundhouse.",
      "Selbstverteidigung: effektiver Abstand-Halter.",
    ],
    priorityScore: 7,
    frequencyScore: 5,
    diversityGroup: "linear-kick",
    videoSearchQuery: "Side kick kickboxing technique tutorial",
  },
  {
    id: "kb_spinning_back_kick",
    slug: "spinning-back-kick",
    name: "Spinning Back Kick",
    category: "boxing",
    difficulty: "pro",
    description:
      "Der Spinning Back Kick ist eine 180°-Drehung mit einer Fersen-Schuss nach hinten. Blinder Kick mit enormer Kraft — erfordert präzises Timing und Gleichgewicht.",
    steps: [
      "Aus dem Stand: Körper beginnt die Drehung mit dem hinteren Fuß.",
      "Blick über die Schulter zum Ziel während der Drehung.",
      "Knie des Schlagbeins anziehen beim Drehen.",
      "Ferse explosiv nach hinten in das Ziel schießen.",
      "Rückkehr in Deckung — Standfuß stabilisiert nach der Drehung.",
    ],
    commonMistakes: [
      "Kein Blick über die Schulter → blinder Kick ohne Zielen.",
      "Drehung zu langsam → Gegner sieht es und weicht aus.",
      "Knie nicht angezogen → Kick wird ein Beinschlenker.",
      "Nach dem Kick kein stabiler Stand.",
    ],
    usage:
      "Überraschungs- und Kontertechnik mit KO-Potenzial. Wird selten erwartet und trifft mit voller Körperkraft.",
    equipment: ["heavy-bag", "pads", "bodyweight"],
    relatedTechniqueIds: [],
    disciplines: ["kickboxen", "karate", "muay-thai"],
    trainingArea: ["kicks", "stand-up"],
    role: "specialist",
    level: "pro",
    alternativeNames: ["Back Kick", "Ushiro Geri", "Rückwärtskick"],
    coachingCues: [
      "Blick über die Schulter ZUERST — dann Kick.",
      "Drehung beginnt mit dem hinteren Fuß als Pivot.",
      "Knie anziehen gibt Geschwindigkeit und Präzision.",
      "Ferse zum Ziel: Bauch oder Brust des Gegners.",
    ],
    safetyNotes: [
      "Nur mit erfahrenen Sparring-Partnern üben — Kontrolle schwierig.",
    ],
    useCases: [
      "Überraschungsangriff aus dem Nahkampf.",
      "Konter wenn Gegner seitlich ist.",
      "Highlight-Technik im Wettkampf.",
    ],
    priorityScore: 5,
    frequencyScore: 3,
    diversityGroup: "spinning-kick",
    videoSearchQuery: "Spinning back kick kickboxing tutorial",
  },
  {
    id: "kb_axe_kick",
    slug: "axe-kick",
    name: "Axe Kick",
    category: "boxing",
    difficulty: "pro",
    description:
      "Der Axe Kick schlägt wie eine Axt von oben nach unten auf Schulter, Schlüsselbein oder Kopf des Gegners. Atypische Trefferlinie — schwer zu blocken.",
    steps: [
      "Bein nach vorn und oben schießen — möglichst hoch.",
      "Ferse wird nach unten geschlagen wie eine Axt.",
      "Kontaktfläche: Ferse oder Hinterseite des Beins.",
      "Ziel: Schulter, Schlüsselbein oder Kopf des Gegners.",
      "Bein kommt nach unten — sofort Deckung zurück.",
    ],
    commonMistakes: [
      "Bein nicht hoch genug angehoben → kein Fallmoment.",
      "Keine Hüftflexibilität → Kick bleibt auf Brusthöhe.",
      "Standbein steif → kein Balance nach dem Kick.",
      "Kein Zielen — Axe Kick trifft oft nichts.",
    ],
    usage:
      "Unorthodoxe Technik gegen Gegner mit hoher Deckung. Kommt von oben über die Arme hinweg.",
    equipment: ["heavy-bag", "pads", "bodyweight"],
    relatedTechniqueIds: [],
    disciplines: ["kickboxen", "karate", "fitness-kickboxen"],
    trainingArea: ["kicks", "stand-up"],
    role: "specialist",
    level: "pro",
    alternativeNames: ["Hammer Kick", "Fersenschlag", "Falling Kick"],
    coachingCues: [
      "Bein hoch: je höher der Schwung, desto stärker der Fallmoment.",
      "Ferse zeigt nach unten beim Kontakt.",
      "Standfuß leicht gebeugt für Balance nach dem Kick.",
      "Gegen hohe Deckungen: Kick kommt von oben drüber.",
    ],
    safetyNotes: [
      "Schlüsselbein-Treffer können bei starkem Kick zu Verletzungen führen.",
    ],
    useCases: [
      "Gegen Gegner mit sehr hoher, geschlossener Deckung.",
      "Überraschungstechnik auf unerwarteter Trefferlinie.",
      "Kombination mit Roundhouse auf anderer Seite.",
    ],
    priorityScore: 4,
    frequencyScore: 2,
    diversityGroup: "linear-kick",
    videoSearchQuery: "Axe kick kickboxing technique tutorial",
  },
  {
    id: "kb_front_kick",
    slug: "front-kick",
    name: "Front Kick (Snap)",
    category: "boxing",
    difficulty: "anfaenger",
    description:
      "Der Front Kick (Snap) schießt den Fuß geradlinig mit Schnappbewegung nach vorn. Distanzwaffe mit Überraschungselement — anders als der Teep fokussiert auf Schnelligkeit.",
    steps: [
      "Knie des Schlagbeins schnell hochziehen.",
      "Fuß schnappt aus dem Knie nach vorn.",
      "Kontaktfläche: Fußballen auf Bauch, Brust oder Kinn.",
      "Fuß sofort zurückschnappen nach dem Kontakt.",
      "Bein zurück, Deckung halten.",
    ],
    commonMistakes: [
      "Kein Schnapp aus dem Knie → Stoß statt Kick.",
      "Hüfte bleibt zurück → schwacher Kontakt.",
      "Fuß zu langsam zurück → Bein kann gegriffen werden.",
      "Deckung sinkt während des Kicks.",
    ],
    usage:
      "Schneller Distanzschuss auf Bauch oder Kinn. Überrascht mit Geschwindigkeit, wenn Gegner flache Deckung hat.",
    equipment: ["heavy-bag", "pads", "bodyweight"],
    relatedTechniqueIds: [],
    disciplines: ["kickboxen", "karate", "fitness-kickboxen", "self-defense"],
    trainingArea: ["kicks", "stand-up"],
    role: "support",
    level: "anfaenger",
    alternativeNames: ["Mae Geri", "Frontkick", "Snap Kick"],
    coachingCues: [
      "Schnapp aus dem Knie: Oberschenkel fix, Unterschenkel schnappt.",
      "Knie zuerst hochziehen — Power kommt vom Kniewinkel.",
      "Sofortiger Rückzug: Bein bleibt nicht draußen.",
      "Hüfte schiebt leicht mit für mehr Reichweite.",
    ],
    safetyNotes: [],
    useCases: [
      "Schnelle Distanzwaffe für Übergangsmomente.",
      "Kinn-Kick wenn Gegner sich vorbeugt.",
      "Combo-Element: Jab-Front Kick als Zwei-Ebenen-Angriff.",
    ],
    priorityScore: 7,
    frequencyScore: 6,
    diversityGroup: "front-kick",
    videoSearchQuery: "Front kick snap kick kickboxing tutorial",
  },
  {
    id: "kb_spinning_hook_kick",
    slug: "spinning-hook-kick",
    name: "Spinning Hook Kick",
    category: "boxing",
    difficulty: "pro",
    description:
      "Der Spinning Hook Kick dreht sich 180° und trifft mit der Ferse oder Sohle den Kopf des Gegners aus einer bogenförmigen Trajektorie. Extrem schwer zu verteidigen wenn gut getimed.",
    steps: [
      "Körper dreht sich 180° mit dem hinteren Fuß als Pivot.",
      "Blick über die Schulter zum Gegner während der Drehung.",
      "Schlagbein kommt im Halbkreis von innen nach außen.",
      "Ferse oder Sohle trifft die Schläfe oder den Kopf.",
      "Drehung ausspielen — Deckung zurücknehmen.",
    ],
    commonMistakes: [
      "Keine Blickführung → trifft nichts.",
      "Drehung zu langsam → Gegner sieht es kommen.",
      "Bein kommt nicht in der richtigen Höhe → Treffer zu tief.",
      "Standfuß instabil nach der Drehung.",
    ],
    usage:
      "Hochspektakulärer Konter und Überraschungskick mit KO-Potenzial. Für Fortgeschrittene und Wettkämpfer.",
    equipment: ["heavy-bag", "pads"],
    relatedTechniqueIds: [],
    disciplines: ["kickboxen", "karate", "muay-thai"],
    trainingArea: ["kicks", "stand-up"],
    role: "specialist",
    level: "pro",
    alternativeNames: ["Wheel Kick", "Spinning Heel Kick", "Reverse Hook Kick"],
    coachingCues: [
      "Blick über die Schulter leitet die Drehung.",
      "Pivot auf dem Standfuß: sanft und kontrolliert.",
      "Bein kommt im Halbkreis: von innen kommend, nicht seitlich.",
      "Ferse als Kontaktfläche: maximaler Schaden auf kleiner Fläche.",
    ],
    safetyNotes: [
      "Nur mit erfahrenen Partnern — Kontrolle beim Spinning Kick sehr schwierig.",
    ],
    useCases: [
      "Konter nach einem Jab des Gegners.",
      "Überraschungsangriff wenn Gegner die Drehung nicht erwartet.",
      "Wettkampf: Highlight-Technik bei passendem Timing.",
    ],
    priorityScore: 4,
    frequencyScore: 2,
    diversityGroup: "spinning-kick",
    videoSearchQuery: "Spinning hook kick kickboxing wheel kick tutorial",
  },
  {
    id: "kb_push_kick_combo",
    slug: "push-kick-combo",
    name: "Push Kick → Cross Combo",
    category: "boxing",
    difficulty: "fortgeschritten",
    description:
      "Klassische Kickboxen-Kombo: Push Kick öffnet die Distanz, Cross trifft wenn Gegner zurückkommt. Timing-Kombo mit Kick und Punch.",
    steps: [
      "Push Kick auf Bauch oder Brust: Gegner wird zurückgedrängt.",
      "Schlagbein landet vorn — sofort Cross schießen.",
      "Cross trifft den Gegner beim Zurückkommen oder Aufrichten.",
      "Hüfte voll im Cross-Einsatz.",
      "Sofort Deckung zurück nach dem Cross.",
    ],
    commonMistakes: [
      "Pause zwischen Kick und Punch → Gegner kommt zurück.",
      "Cross ohne Hüftdreh nach dem Kick.",
      "Deckung sinkt während der Kombination.",
      "Schlagbein nicht schnell genug zurück → Cross-Basis fehlt.",
    ],
    usage:
      "Zwei-Waffen-Kombination: Bein und Faust. Klassisches Kickboxen-Timing-Duo.",
    equipment: ["heavy-bag", "pads"],
    techniqueIds: ["kb_front_kick", "boxing_cross"],
    relatedTechniqueIds: [],
    disciplines: ["kickboxen", "muay-thai", "mma", "fitness-kickboxen"],
    trainingArea: ["combos", "kicks", "punches"],
    role: "combo",
    level: "fortgeschritten",
    alternativeNames: ["Kick-Punch Combo", "Front Kick Cross"],
    coachingCues: [
      "Kick-Landung ist der Startschuss für den Cross.",
      "Übergang ohne Pause: Bein landet, Cross schießt.",
      "Hüfteinsatz im Cross — nicht nur Arm.",
      "Deckung zwischen Kick und Cross nicht fallen lassen.",
    ],
    safetyNotes: [],
    useCases: [
      "Gegen Gegner, die auf Kicks zum Angriff wechseln.",
      "Timing-Training: Kick + Punch sequencing.",
      "Druckabbau: Kick schiebt zurück, Cross stoppt erneutes Kommen.",
    ],
    priorityScore: 7,
    frequencyScore: 7,
    diversityGroup: "combo",
    videoSearchQuery: "Kickboxing front kick cross combination tutorial",
  },
  {
    id: "kb_low_high_kick_combo",
    slug: "low-high-kick-combo",
    name: "Low Kick → High Kick Combo",
    category: "boxing",
    difficulty: "pro",
    description:
      "Classic level-change Kick-Kombo: Low Kick zum Bein senkt die Deckung des Gegners, dann sofort High Kick zum Kopf. Erfordert hohe Flexibilität.",
    steps: [
      "Low Kick auf den Oberschenkel des Gegners.",
      "Gegner senkt die Deckung oder zieht das Bein hoch.",
      "Sofort High Kick mit demselben oder dem anderen Bein.",
      "High Kick trifft den Kopf — Deckung ist unten.",
      "Sofort Deckung zurück nach dem High Kick.",
    ],
    commonMistakes: [
      "Pause zwischen Low und High Kick → Gegner sieht den High Kick.",
      "High Kick ohne ausreichende Flexibilität → trifft Schulter.",
      "Deckung senkst sich beim High Kick.",
      "Schlechtes Timing: Gegner hat Deckung bereits wieder oben.",
    ],
    usage:
      "Level-Change-Technik: zwingt den Gegner, zwei verschiedene Levels gleichzeitig zu verteidigen.",
    equipment: ["heavy-bag", "pads"],
    techniqueIds: ["muaythai_low_kick", "kb_high_kick"],
    relatedTechniqueIds: [],
    disciplines: ["kickboxen", "muay-thai"],
    trainingArea: ["combos", "kicks"],
    role: "combo",
    level: "pro",
    alternativeNames: ["Low-High", "Level-Change Kick Combo"],
    coachingCues: [
      "Low Kick muss sitzen: Reaktion des Gegners ist entscheidend.",
      "Kein Reset zwischen Kicks — direkt hoch.",
      "Gleiche Seite: Low Kick links + High Kick links für Überraschung.",
      "Flexibilität: ohne Dehntraining ist der High Kick nicht möglich.",
    ],
    safetyNotes: [
      "Ausreichende Hüftflexibilität ist Grundvoraussetzung.",
    ],
    useCases: [
      "Level-Change zur Erzeugung von Öffnungen.",
      "Gegen Gegner, die reflexartig auf Low Kicks reagieren.",
      "Wettkampf-Kombo mit KO-Potenzial.",
    ],
    priorityScore: 7,
    frequencyScore: 5,
    diversityGroup: "combo",
    videoSearchQuery: "Low kick high kick combination kickboxing tutorial",
  },
];
