import type { Technique } from "../types";

/**
 * MMA-spezifische Techniken — keine Disziplinen-Kopien, sondern echte
 * MMA-Hybridtechniken, die aus der Kombination von Stand-Up, Clinch und
 * Grappling entstehen.
 */
export const MMA_BASIC_TECHNIQUES: Technique[] = [
  {
    id: "mma_clinch_knee",
    slug: "clinch-knee-mma",
    name: "Clinch Knee MMA",
    category: "boxing",
    difficulty: "fortgeschritten",
    description:
      "Der MMA-Clinch-Knie ist eine Hybridtechnik: aus dem Collar Tie oder Dirty Boxing wird ein kurzes Knie auf Bauch oder Kopf gesetzt. Kurz, scharf, in Schlagdistanz.",
    steps: [
      "Einen Arm um den Hals oder Hinterkopf des Gegners.",
      "Andere Hand kontrolliert den Arm oder Ellbogen des Gegners.",
      "Standfuß fest, Hüfte schiebt nach vorn.",
      "Knie schießt auf Bauch oder Solar plexus.",
      "Sofort aus der Clinch-Position heraustreten oder weiterboxen.",
    ],
    commonMistakes: [
      "Zu wenig Kontrolle vor dem Knie → Gegner weicht aus.",
      "Hüfte nicht mit nach vorn → schwacher Knie.",
      "Knie zu weit → wird ein Kick, kein Knie.",
      "Nach dem Knie keine Folgeaktion oder Rückzug.",
    ],
    usage:
      "Nahdistanz-Waffe aus dem Dirty Boxing oder Tie-Up. Unterbricht Pressing-Gegner und schafft Abstand.",
    equipment: ["heavy-bag", "pads", "mat"],
    relatedTechniqueIds: [],
    disciplines: ["mma", "muay-thai"],
    trainingArea: ["knees", "clinch"],
    role: "core",
    level: "fortgeschritten",
    alternativeNames: ["MMA Clinch Knee", "Dirty Clinch Knee", "Nahkampf-Knie"],
    coachingCues: [
      "Griff zuerst: Knie ohne Kontrolle trifft nichts.",
      "Hüfte nach vorn: der Knie kommt von der Hüfte, nicht nur dem Bein.",
      "Kurz und scharf: kein langer Schwung.",
      "Nach dem Knie: Distanz schaffen oder in Kombination weiterboxen.",
    ],
    safetyNotes: [
      "Knie in der Clinch-Situation: immer vorher ankündigen im Training.",
    ],
    useCases: [
      "Aus dem Clinch nach Jab-Cross-Eingang.",
      "Gegen Gegner, die auf Schläge warten: Knie unerwartet.",
      "MMA-Übergang: Clinch → Knee → Takedown oder Distanz.",
    ],
    priorityScore: 8,
    frequencyScore: 7,
    diversityGroup: "clinch-weapon",
    videoSearchQuery: "MMA clinch knee dirty boxing tutorial",
  },
  {
    id: "mma_cage_control",
    slug: "cage-control",
    name: "Cage Control",
    category: "wrestling",
    difficulty: "fortgeschritten",
    description:
      "Cage Control ist die Kunst, die Wand des MMA-Käfigs taktisch zu nutzen — defensiv zum Aufhalten von Takedowns, offensiv zum Erzwingen von Positionen.",
    steps: [
      "Rücken zur Wand: eine Hand zur Wand stützen, tief in den Stand gehen.",
      "Hüfte tief — Gegner kann nicht unter den Schwerpunkt kommen.",
      "Underhook kämpfen: wer die Underhooks hat, kontrolliert die Wand.",
      "Offensiv: Gegner mit Bodylock zur Wand pressen, Hüfte randrücken.",
      "Finish: aus der Wand-Kontrolle Knie, Elbow oder Takedown.",
    ],
    commonMistakes: [
      "Rücken zur Wand ohne aktive Beinarbeit → Gegner kommt rein.",
      "Zu aufrechter Stand gegen die Wand → Takedown möglich.",
      "Underhooks passiv: nicht aktiv kämpfen.",
      "Kein Raustreten aus der Wand wenn möglich.",
    ],
    usage:
      "Taktische Fundamentaltechnik in der MMA-Cage-Umgebung. Unterscheidet MMA von anderen Disziplinen.",
    equipment: ["mat"],
    relatedTechniqueIds: [],
    disciplines: ["mma"],
    trainingArea: ["clinch", "takedown-defense"],
    role: "specialist",
    level: "fortgeschritten",
    alternativeNames: ["Wall Work", "Cage Wrestling", "Clinch Against Fence"],
    coachingCues: [
      "Hüfte tief: unterhalb des Schwerpunkts des Gegners sein.",
      "Aktive Beinarbeit: nicht statisch gegen die Wand lehnen.",
      "Underhook ist Schlüssel: Double-Underhook = Kontrolle.",
      "Aus der Wand rausdrehen wenn Gelegenheit da ist.",
    ],
    safetyNotes: [],
    useCases: [
      "Takedown-Abwehr gegen die Wand.",
      "Clinch-Kontrolle: Knie und Ellbogen aus der Wand-Position.",
      "Übergang Wand → Takedown wenn Gegner müde wird.",
    ],
    priorityScore: 9,
    frequencyScore: 8,
    diversityGroup: "mma-position",
    videoSearchQuery: "MMA cage control wall work clinch tutorial",
  },
  {
    id: "mma_ground_and_pound",
    slug: "ground-and-pound",
    name: "Ground and Pound",
    category: "boxing",
    difficulty: "fortgeschritten",
    description:
      "Ground and Pound ist das Schlagen auf den am Boden liegenden Gegner aus einer dominanten Bodenposition. Erfordert Positionskontrolle und Schlag-Koordination.",
    steps: [
      "Dominante Position sichern: Mount, Half Guard oder Side Control.",
      "Eigenes Gewicht auf den Gegner verteilen — keine leeren Räume.",
      "Schläge auf Körper oder Gesicht des Gegners — kurze, präzise Hammerfists oder Punches.",
      "Freie Hand kontrolliert Arm oder Hals des Gegners.",
      "Position halten: nach jedem Schlag zurück in sichere Deckung.",
    ],
    commonMistakes: [
      "Position verloren durch übereifrigen Schlag — Balance weg.",
      "Beide Hände zum Schlagen → Gegner kann Submission einleiten.",
      "Kein Positionserhalt → Gegner macht Escape.",
      "Schläge von zu weit weg → kein Kontakt, eigene Balance weg.",
    ],
    usage:
      "Finish-Technik aus dominanter Bodenposition. Zwingt Gegner zur Tap oder zum Ref-Stoppage.",
    equipment: ["mat", "heavy-bag"],
    relatedTechniqueIds: [],
    disciplines: ["mma"],
    trainingArea: ["ground-control", "punches"],
    role: "core",
    level: "fortgeschritten",
    alternativeNames: ["GnP", "Punches from Top", "Hammerfists"],
    coachingCues: [
      "Position zuerst, Schläge danach — nie umgekehrt.",
      "Eine Hand kontrolliert, eine Hand schlägt.",
      "Kurze Schläge: lange Schläge kosten die Position.",
      "Körpergewicht runter: keinen Luftraum geben.",
    ],
    safetyNotes: [
      "Im Training mit stark reduzierten Schlägen oder nur Touches trainieren.",
    ],
    useCases: [
      "Finish aus Mount oder Side Control.",
      "Zwingen des Gegners zu unvorteilhaften Reactionen (Guard, Submission-Versuch).",
      "Schaffen von Öffnungen für Submissions durch G&P.",
    ],
    priorityScore: 9,
    frequencyScore: 8,
    diversityGroup: "ground-weapon",
    videoSearchQuery: "Ground and pound MMA technique tutorial",
  },
  {
    id: "mma_dirty_boxing",
    slug: "dirty-boxing",
    name: "Dirty Boxing",
    category: "boxing",
    difficulty: "fortgeschritten",
    description:
      "Dirty Boxing ist das Schlagen auf kürzester Distanz aus einem Clinch oder Tie-Up. Kurze Uppercuts, Hammerfists, Body Shots — keine klare Bewegungslinie, maximale Überraschung.",
    steps: [
      "In die Clinch-Distanz eintreten — eine Hand am Hinterkopf oder Hals.",
      "Freie Hand setzt kurze Schläge: Uppercuts, Hooks, Body Shots.",
      "Kein Rückzug für Schläge — alle Schläge aus der Nahdistanz.",
      "Wechseln zwischen Schlägen und Positionskämpfen.",
      "Übergang in Takedown oder Heraustreten aus dem Clinch.",
    ],
    commonMistakes: [
      "Zu viel Abstand für Dirty Boxing: dann ist es normales Boxing.",
      "Kein Griff: Dirty Boxing ohne Kontrolle ist Klingelknöpfchen.",
      "Stationär: Dirty Boxing erfordert ständige Bewegung.",
      "Kein Plan nach dem Clinch: entweder Takedown oder Exit.",
    ],
    usage:
      "Hybridtechnik für die enge Distanz im MMA. Verwirrt Boxer und Wrestler gleichermaßen.",
    equipment: ["pads", "mat"],
    relatedTechniqueIds: [],
    disciplines: ["mma", "boxing"],
    trainingArea: ["clinch", "punches"],
    role: "advanced",
    level: "fortgeschritten",
    alternativeNames: ["Infighting", "Clinch Boxing", "Nahkampf-Boxen"],
    coachingCues: [
      "Griff + Schlag gleichzeitig: eine Hand kontrolliert, eine schlägt.",
      "Kurze, kompakte Schläge: kein Ausholen nötig.",
      "Ständig bewegen: kein statisches Stehen im Clinch.",
      "Entscheidung treffen: Takedown oder Rausdrehen nach dem Clinch.",
    ],
    safetyNotes: [],
    useCases: [
      "Gegen Boxer: Clinch-Distanz, wo sie nicht schlagen können.",
      "Gegen Wrestler: Knees und Schläge als Takedown-Abwehr.",
      "Übergang von Boxing zu Wrestling ohne saubere Trennung.",
    ],
    priorityScore: 8,
    frequencyScore: 7,
    diversityGroup: "clinch-weapon",
    videoSearchQuery: "Dirty boxing MMA clinch fighting tutorial",
  },
  {
    id: "mma_guard_mma",
    slug: "mma-guard",
    name: "MMA Guard",
    category: "bjj",
    difficulty: "fortgeschritten",
    description:
      "Die MMA Guard ist eine angepasste Closed Guard für den Schlagkampf auf dem Boden. Andere Griffe, andere Abstände als im BJJ — Schläge müssen abgewehrt werden.",
    steps: [
      "Geschlossene Beine um den Gegner — aktive Hüfte.",
      "Nicht flach liegen: Schulter leicht angehoben, Deckung für Kopf.",
      "Hände schützen den Kopf gegen Hammerfists und Punches.",
      "Arme des Gegners kontrolieren: einen Arm kontrollieren, anderen abwehren.",
      "Aktiv arbeiten: Sweeps, Submissions oder aufstehen wenn möglich.",
    ],
    commonMistakes: [
      "Flach auf dem Rücken → Kopf ungeschützt für Hammerfists.",
      "Guard wird passiv gehalten → kein Schutz, kein Angriff.",
      "Beide Hände runter → Schläge treffen Gesicht.",
      "Keine Bewegung → Gegner findet Rhythmus für Ground and Pound.",
    ],
    usage:
      "Defensive Grundlage im MMA-Bodenkampf. Ermöglicht Gegenwehr auch von unten gegen einen schlagenden Gegner.",
    equipment: ["mat"],
    relatedTechniqueIds: [],
    disciplines: ["mma", "bjj"],
    trainingArea: ["guard", "defense"],
    role: "core",
    level: "fortgeschritten",
    alternativeNames: ["Full Guard MMA", "Closed Guard MMA", "Bottom Position MMA"],
    coachingCues: [
      "Kopf schützen: Deckung wichtiger als in reinem BJJ.",
      "Aktive Hüfte: nicht warten, sondern ständig Winkel suchen.",
      "Einen Arm des Gegners kontrollieren: macht Schläge halbseitig.",
      "Beine aktiv: Hüfte hoch bringen für Sweeps und Submissions.",
    ],
    safetyNotes: [
      "Im MMA G&P-Training: Kopf niemals ungeschützt — immer mit Partnervereinbarung.",
    ],
    useCases: [
      "Bodenkampf-Schutzposition wenn Takedown nicht verhindert werden konnte.",
      "Ausgangspunkt für Submission-Angriffe.",
      "Übergang zu Technical Stand-Up wenn Gegner aufsteht.",
    ],
    priorityScore: 9,
    frequencyScore: 8,
    diversityGroup: "mma-position",
    videoSearchQuery: "MMA guard bottom position closed guard MMA tutorial",
  },
  {
    id: "mma_sprawl_and_brawl",
    slug: "sprawl-and-brawl",
    name: "Sprawl and Brawl",
    category: "boxing",
    difficulty: "fortgeschritten",
    description:
      "Sprawl and Brawl ist die MMA-Strategie: Takedown-Versuche mit dem Sprawl abwehren und sofort in Stand-Up-Angriffe übergehen. Wrestling-Defense + Boxing kombiniert.",
    steps: [
      "Gegner schießt einen Takedown — sofort Beine nach hinten.",
      "Hüfte nach unten auf den Gegner: Sprawl.",
      "Aus der Sprawl-Position: Gegner kontrollieren (Front-Headlock).",
      "Entweder Schläge von oben oder Gegner aufstehen lassen für Stand-Up.",
      "Zurück in Boxstellung — Distanz wieder herstellen.",
    ],
    commonMistakes: [
      "Sprawl zu spät → Gegner kommt rein.",
      "Nach dem Sprawl keine Folgeaktion → Gegner steht wieder auf.",
      "Front-Headlock nicht fixiert → kein Kontrolle.",
      "Zu lange am Boden — Strategie ist Stand-Up, nicht Boden.",
    ],
    usage:
      "Strategie und Technik kombiniert: Takedown-Resistenz + Striking-Dominanz im Stand. Klassisches Boxer-in-MMA-Profil.",
    equipment: ["mat", "pads"],
    relatedTechniqueIds: [],
    disciplines: ["mma", "boxing", "wrestling"],
    trainingArea: ["takedown-defense", "stand-up"],
    role: "advanced",
    level: "fortgeschritten",
    alternativeNames: ["Sprawl Defense + Boxing", "Anti-Takedown Strategy"],
    coachingCues: [
      "Sprawl-Reaktion muss automatisch sein — ohne Nachdenken.",
      "Hüfte auf den Gegner: Körpergewicht ist die Waffe.",
      "Sofort Folgeaktion nach dem Sprawl.",
      "Stand-Up ist das Ziel: am Boden bleiben schadet dem Springer.",
    ],
    safetyNotes: [],
    useCases: [
      "Boxer-Strategie in MMA: Kämpfer auf Distanz halten.",
      "Takedown-Abwehr mit sofortigem Gegenangriff kombinieren.",
      "Grundlage für alle MMA-Kämpfer, die ihre Striking-Basis schützen wollen.",
    ],
    priorityScore: 9,
    frequencyScore: 8,
    diversityGroup: "mma-strategy",
    videoSearchQuery: "Sprawl and brawl MMA strategy wrestling defense tutorial",
  },
  {
    id: "mma_takedown_defense_mma",
    slug: "takedown-defense-mma",
    name: "Takedown Defense MMA",
    category: "wrestling",
    difficulty: "fortgeschritten",
    description:
      "Takedown-Abwehr im MMA kombiniert klassisches Wrestling (Sprawl, Whizzer) mit dem MMA-spezifischen Drehen, Ringen gegen die Wand und Übergang in Angriff.",
    steps: [
      "Gegner schießt: Sprawl, Beine nach hinten, Hüfte raus.",
      "Hände auf Hinterkopf des Gegners — nach unten drücken.",
      "Alternative: Whizzer — eigener Arm über den gegnerischen, von innen nach außen drehen.",
      "Aus Sprawl: Front-Headlock oder Guillotine ansetzen.",
      "Aufstehen und Distanz herstellen oder Schläge von oben setzen.",
    ],
    commonMistakes: [
      "Sprawl reagiert zu langsam.",
      "Kein Folge-Move nach dem Sprawl.",
      "Whizzer zu schwach: kein Drehmoment.",
      "Am Boden bleiben statt aufzustehen.",
    ],
    usage:
      "Fundamentale Abwehrtechnik in MMA. Jeder Striker muss Takedown-Defense beherrschen.",
    equipment: ["mat"],
    relatedTechniqueIds: [],
    disciplines: ["mma", "wrestling"],
    trainingArea: ["takedown-defense", "transitions"],
    role: "core",
    level: "fortgeschritten",
    alternativeNames: ["TD Defense", "Anti-Takedown MMA", "Sprawl Defense MMA"],
    coachingCues: [
      "Sprawl-Reflex trainieren: Partner-Drills täglich.",
      "Whizzer: Arm über Gegners Arm, nach außen drehen.",
      "Hüfte IMMER tief: hohe Hüfte = erfolgreiches Takedown.",
      "Ziel: Boden vermeiden — aufstehen ist immer die Option.",
    ],
    safetyNotes: [],
    useCases: [
      "Striker-Strategie: Takedowns verhindern, Boxing behalten.",
      "MMA-Grundlage: kein Striker ist ohne Takedown-Defense vollständig.",
      "Cage-Situationen: Abwehr gegen die Wand.",
    ],
    priorityScore: 10,
    frequencyScore: 9,
    diversityGroup: "takedown-defense",
    videoSearchQuery: "MMA takedown defense sprawl whizzer tutorial",
  },
  {
    id: "mma_transition_takedown_guard",
    slug: "transition-takedown-to-guard",
    name: "Transition: Takedown → Bodenkontrolle",
    category: "wrestling",
    difficulty: "pro",
    description:
      "Der Übergang nach einem erfolgreichen Takedown in eine dominante Bodenposition — Half Guard passieren, Side Control fixieren oder direkt in Mount übergehen.",
    steps: [
      "Nach dem Takedown: Gegner landet auf dem Rücken oder der Seite.",
      "Eigene Position stabilisieren: Körpergewicht auf den Gegner.",
      "Half Guard passieren: Bein des Gegners aus dem Halbklammergriff befreien.",
      "Side Control fixieren: Brust auf Brust, Hüfte tief, Griffe sichern.",
      "Optional: von Side Control in Mount übergehen.",
    ],
    commonMistakes: [
      "Nach dem Takedown kein sofortiges Fixieren → Gegner recovert.",
      "Aufrecht bleiben statt niedrig → Gegner kann aufstehen.",
      "Half Guard zu langsam passieren → Gegner zieht Guard.",
      "Side Control ohne Hüftdruck → Gegner kann shrimpen.",
    ],
    usage:
      "Kritischer Übergangsmoment: nach dem Takedown entscheidet sich, wer die Kontrolle behält.",
    equipment: ["mat"],
    relatedTechniqueIds: [],
    disciplines: ["mma", "bjj", "wrestling"],
    trainingArea: ["transitions", "ground-control"],
    role: "advanced",
    level: "pro",
    alternativeNames: ["Pass to Control", "Takedown → Top Position"],
    coachingCues: [
      "Sofort nach dem Takedown: Körpergewicht auf den Gegner.",
      "Tief bleiben: keine Lücken für den Gegner.",
      "Half Guard passieren: Knie durch die Beine, nicht über sie.",
      "Side Control: Hüftkontrolle ist wichtiger als Armkontrolle.",
    ],
    safetyNotes: [],
    useCases: [
      "Nach erfolgreichen Takedowns sofortige Kontrolle sichern.",
      "MMA: Übergang von Takedown zu Ground and Pound.",
      "BJJ: Übergang von Takedown zu Submission-Angriffen.",
    ],
    priorityScore: 8,
    frequencyScore: 7,
    diversityGroup: "transition",
    videoSearchQuery: "MMA takedown to ground control transition tutorial",
  },
];
