import type { Technique } from "../types";

export const MUAY_THAI_TECHNIQUES: Technique[] = [
  // ─── Anfänger ────────────────────────────────────────────────────────────
  {
    id: "muaythai_teep",
    slug: "teep",
    name: "Teep (Push Kick)",
    category: "muay-thai",
    difficulty: "anfaenger",
    description:
      "Der Teep ist der 'Jab des Beins' — ein Frontkick zur Distanz, zum Stoppen und zum Setup. Pflicht-Technik in jedem Muay-Thai-Kampf.",
    steps: [
      "Aus dem Stand: Knie des Schlagbeins explosiv anziehen.",
      "Hüfte schiebt nach vorn.",
      "Fuß schießt geradlinig auf Bauch oder Brust des Gegners.",
      "Kontaktstelle: Fußballen oder ganze Sohle.",
      "Sofort zurückziehen, Bein wieder in Stellung.",
    ],
    commonMistakes: [
      "Hüfte nicht mit nach vorn → kein Druck im Kick.",
      "Fuß zur Seite gedreht → kein gerader Push.",
      "Knie nicht hoch genug angezogen → niedriger, schwacher Kick.",
      "Stützbein steif — niemals gestreckt halten.",
    ],
    usage:
      "Distanz halten, Gegner stoppen, Kombinationen einleiten oder unterbrechen. Im Wettkampf zur Punktegewinnung.",
    equipment: ["heavy-bag", "pads", "bodyweight"],
    relatedTechniqueIds: ["muaythai_low_kick", "muaythai_roundhouse"],
    nextTechniqueId: "muaythai_low_kick",
    disciplines: ["muay-thai", "mma", "kickboxen"],
    trainingArea: ["kicks", "stand-up"],
    role: "core",
    level: "anfaenger",
    alternativeNames: ["Push Kick", "Front Kick", "Frontkick"],
    coachingCues: [
      "Knie zuerst hochziehen — dann erst strecken.",
      "Hüfte schiebt nach vorn: Power kommt nicht aus dem Bein, sondern der Hüfte.",
      "Kontakt mit dem Fußballen, nicht dem Spann.",
      "Stützknie weich — nie gestreckt beim Kick.",
    ],
    safetyNotes: [],
    useCases: [
      "Distanz-Waffe gegen Druckgegner.",
      "Stop-Kick: Gegner beim Angriff stoppen.",
      "Setup für Roundhouse: Teep → Low Kick.",
    ],
    priorityScore: 9,
    frequencyScore: 9,
    diversityGroup: "front-kick",
    videoSearchQuery: "Teep push kick Muay Thai tutorial",
  },
  {
    id: "muaythai_low_kick",
    slug: "low-kick",
    name: "Low Kick",
    category: "muay-thai",
    difficulty: "anfaenger",
    description:
      "Der Schienbein-Kick auf Oberschenkel oder Wade des Gegners. Zermürbt das Standbein und führt oft zum K.O.-Setup.",
    steps: [
      "Standfuß dreht 45° nach außen — Hüfte folgt.",
      "Schlagbein kommt im Bogen mit voller Hüftrotation.",
      "Kontaktfläche: Schienbein (nicht Spann!).",
      "Trefferpunkt: Außenseite des Oberschenkels oder Wade.",
      "Bein zurückziehen oder nach Treffer Folge-Combo.",
    ],
    commonMistakes: [
      "Standfuß nicht gedreht → keine Hüftrotation, schwacher Kick.",
      "Mit Spann statt Schienbein → Verletzungsrisiko.",
      "Oberkörper bleibt aufrecht → keine Power.",
      "Kein Folge-Move — der Kick ist Setup, nicht Endpunkt.",
    ],
    usage:
      "Zermürbt das Standbein des Gegners über den Verlauf des Kampfes. Klassischer Damage-Dealer in Muay Thai und MMA.",
    equipment: ["heavy-bag", "pads", "bodyweight"],
    relatedTechniqueIds: ["muaythai_roundhouse", "muaythai_teep"],
    nextTechniqueId: "muaythai_roundhouse",
    disciplines: ["muay-thai", "kickboxen", "mma", "fitness-kickboxen"],
    trainingArea: ["kicks", "stand-up"],
    role: "core",
    level: "anfaenger",
    alternativeNames: ["Leg Kick", "Calf Kick", "Unterschenkelkick"],
    coachingCues: [
      "Standfuß 45° drehen — diese Bewegung aktiviert die Hüftrotation.",
      "Schienbein als Werkzeug: härter als der Fuß, keine Verletzungsgefahr.",
      "Trefferziel: äußerer Oberschenkel oder Wade.",
      "Oberkörper rotiert mit: kein aufrechter Rumpf.",
    ],
    safetyNotes: [
      "Schienbein-Conditioning regelmäßig trainieren — sonst Verletzungsrisiko beim Schlagen.",
    ],
    useCases: [
      "Zermürben des Standbeins über mehrere Runden.",
      "Setup: Low Kick + Cross als Kombo.",
      "MMA: Leg Kick gegen Wrestler, um ihre Mobilität zu reduzieren.",
    ],
    priorityScore: 9,
    frequencyScore: 9,
    diversityGroup: "leg-kick",
    videoSearchQuery: "Low kick leg kick Muay Thai tutorial",
  },
  {
    id: "muaythai_roundhouse",
    slug: "roundhouse",
    name: "Roundhouse Kick",
    category: "muay-thai",
    difficulty: "anfaenger",
    description:
      "Der Power-Kick aus Muay Thai — volle Hüftrotation, Schienbein als Aufprallfläche, Ziel: Körper, Arme oder Kopf.",
    steps: [
      "Standfuß dreht 90° nach außen.",
      "Schlagbein kommt nicht aus dem Knie — die Hüfte rotiert das ganze Bein durch.",
      "Schienbein trifft das Ziel mit voller Rotation.",
      "Oberkörper rotiert mit, freie Hand schwingt nach hinten für Ausgleich.",
      "Bein folgt durch oder kommt schnell zurück.",
    ],
    commonMistakes: [
      "Aus dem Knie tritt — kein Hüft-Drive.",
      "Standfuß starr — Knie-Verletzungsrisiko.",
      "Hände sinken während des Kicks.",
      "Gleichgewicht verloren nach dem Kick.",
    ],
    usage:
      "Schwerer Kick zum Body oder Kopf. Im MMA der gefährlichste Stand-Kick gegen Wrestler.",
    equipment: ["heavy-bag", "pads", "bodyweight"],
    relatedTechniqueIds: ["muaythai_teep", "muaythai_low_kick"],
    nextTechniqueId: "muaythai_knee",
    disciplines: ["muay-thai", "kickboxen", "mma", "fitness-kickboxen"],
    trainingArea: ["kicks", "stand-up"],
    role: "core",
    level: "anfaenger",
    alternativeNames: ["Thai Kick", "Roundhouse", "Mawashi Geri"],
    coachingCues: [
      "Hüfte dreht das Bein durch — kein Knie-Kick.",
      "Standfuß 90° drehen für volle Hüftbewegung.",
      "Follow-Through: Bein geht durch das Ziel, kein Anhalten.",
      "Freie Hand nach hinten für Balance.",
    ],
    safetyNotes: [
      "Schienbein-Konditionierung für harte Kicks nötig.",
    ],
    useCases: [
      "Body-Kick zum Zermürben der Leber.",
      "Head-Kick als KO-Technik.",
      "MMA: Roundhouse als Takedown-Abwehr bei kommenden Gegnern.",
    ],
    priorityScore: 10,
    frequencyScore: 9,
    diversityGroup: "roundhouse",
    videoSearchQuery: "Roundhouse kick Muay Thai technique tutorial",
  },
  {
    id: "muaythai_knee",
    slug: "knee",
    name: "Knee Strike",
    category: "muay-thai",
    difficulty: "anfaenger",
    description:
      "Der Kniestoß ist die Waffe der Nahdistanz und des Clinches. Hüfte schiebt nach vorn, Knie schießt explosiv ins Ziel.",
    steps: [
      "Aus dem Stand oder Clinch: Standfuß fest am Boden.",
      "Schlagbein zieht das Knie an, Hüfte schiebt nach vorn.",
      "Spitze des Knies trifft Bauch, Solar plexus oder Kopf.",
      "Beim Treffer Hüfte voll durchstrecken.",
      "Bein zurück, Stellung halten.",
    ],
    commonMistakes: [
      "Hüfte nicht mit nach vorn → schwacher Knie.",
      "Knie zu früh — wird zu einem flachen Kick.",
      "Im Clinch nicht den Kopf des Gegners gezogen.",
      "Standfuß instabil — Sturzgefahr.",
    ],
    usage:
      "Hauptwaffe im Clinch. Auch zum Stoppen reinkommender Gegner extrem effektiv.",
    equipment: ["heavy-bag", "pads", "bodyweight"],
    relatedTechniqueIds: ["muaythai_clinch_basic", "muaythai_elbow_basic"],
    nextTechniqueId: "muaythai_clinch_basic",
    disciplines: ["muay-thai", "mma", "fitness-kickboxen"],
    trainingArea: ["knees", "clinch"],
    role: "core",
    level: "anfaenger",
    alternativeNames: ["Knee", "Khao", "Kniestoß"],
    coachingCues: [
      "Hüfte nach vorn: Knie kommt von der Hüftbewegung, nicht nur vom Bein.",
      "Kniespitze als Kontaktfläche — nicht das Schienbein.",
      "Im Clinch: Kopf des Gegners nach unten ziehen.",
      "Standfuß auf Fußballen: Balance und Mobility.",
    ],
    safetyNotes: [],
    useCases: [
      "Hauptangriff im Clinch.",
      "Stop-Technik gegen reinkommende Gegner.",
      "MMA: Knee bei gebeugtem Kopf des Gegners.",
    ],
    priorityScore: 9,
    frequencyScore: 9,
    diversityGroup: "knee",
    videoSearchQuery: "Knee strike Muay Thai clinch tutorial",
  },
  {
    id: "muaythai_clinch_basic",
    slug: "clinch-basic",
    name: "Basic Clinch",
    category: "muay-thai",
    difficulty: "anfaenger",
    description:
      "Der Plum-Clinch (Double-Collar Tie): beide Hände am Hinterkopf des Gegners, Ellbogen zur Mitte. Setup für Knees, Sweeps und Off-Balancing.",
    steps: [
      "Eine Hand zum Hinterkopf greifen.",
      "Andere Hand sofort dazu — beide Hände übereinander am Hinterkopf.",
      "Ellbogen eng zueinander — schließt das Tor zum eigenen Kopf.",
      "Gegnerischen Kopf nach unten ziehen → er kann nicht aufrichten.",
      "Aus der Position Knees oder Off-Balance-Sweeps setzen.",
    ],
    commonMistakes: [
      "Hände nebeneinander statt übereinander → kein Druck nach unten.",
      "Ellbogen offen → Gegner setzt Hooks oder Uppercuts.",
      "Gegnerischen Kopf nicht nach unten gezogen → er rotiert raus.",
      "Stille Position — im Clinch muss ständig gearbeitet werden.",
    ],
    usage:
      "Zentrale Nahdistanz-Position in Muay Thai. Auch in MMA gegen die Wand stark.",
    equipment: ["mat", "bodyweight"],
    relatedTechniqueIds: ["muaythai_knee", "muaythai_elbow_basic"],
    disciplines: ["muay-thai", "mma"],
    trainingArea: ["clinch", "knees"],
    role: "core",
    level: "anfaenger",
    alternativeNames: ["Plum Clinch", "Double Collar Tie", "Muay Thai Clinch"],
    coachingCues: [
      "Hände übereinander: untere Hand stabilisiert, obere zieht.",
      "Ellbogen eng: ein Rahmen für den eigenen Kopf.",
      "Gegner nach unten ziehen: er kann kein Knie setzen wenn sein Kopf unten ist.",
      "Aktiv bleiben: immer Knees, Sweeps oder Position ändern.",
    ],
    safetyNotes: [],
    useCases: [
      "Clinch-Dominanz im Nahkampf.",
      "MMA: Clinch-Knees gegen die Wand.",
      "Sweep-Setup: Off-Balance aus dem Clinch.",
    ],
    priorityScore: 9,
    frequencyScore: 9,
    diversityGroup: "clinch",
    videoSearchQuery: "Muay Thai plum clinch tutorial",
  },
  {
    id: "muaythai_elbow_basic",
    slug: "elbow-basic",
    name: "Elbow Basics",
    category: "muay-thai",
    difficulty: "anfaenger",
    description:
      "Der Ellbogen ist die schärfste Waffe in Muay Thai — kurze Distanz, hoher Schaden. Standardvariante: horizontaler Slash.",
    steps: [
      "Aus dem Stand oder Clinch: Schulter rotiert in Schlagrichtung.",
      "Ellbogen zeigt zum Ziel, Arm gewinkelt 45°.",
      "Aufprallfläche: Spitze oder Kante des Ellbogens.",
      "Hüfte rotiert mit, Schulter deckt das Kinn.",
      "Sofort zurück in Deckung — Ellbogen lässt offen.",
    ],
    commonMistakes: [
      "Schulterdreh fehlt → Schlag aus dem Arm.",
      "Ellbogen nicht spitz → Schaden minimal.",
      "Andere Hand sinkt während des Schlags.",
      "Distanz falsch — Ellbogen funktioniert nur in Nähe.",
    ],
    usage:
      "Im Clinch oder bei plötzlichen Distanzschlüssen. Konflikt-beendend, wenn er sitzt.",
    equipment: ["heavy-bag", "pads", "bodyweight"],
    relatedTechniqueIds: ["muaythai_knee", "muaythai_clinch_basic"],
    disciplines: ["muay-thai", "mma"],
    trainingArea: ["elbows", "clinch"],
    role: "core",
    level: "anfaenger",
    alternativeNames: ["Elbow Strike", "Sok", "Ellbogenschlag"],
    coachingCues: [
      "Schulterrotation ist der Motor des Ellbogens.",
      "Kante des Ellbogens als Schneidewerkzeug — nicht die Spitze.",
      "Kontakt auf der Seite des Kopfes, über den Augenbrauen.",
      "Andere Hand schützt: nie beide Hände zum Ziel.",
    ],
    safetyNotes: [
      "Ellbogen nur mit Schutzausrüstung im Vollkontakt-Sparring.",
    ],
    useCases: [
      "Clinch-Waffe: Ellbogen wenn Knie nicht möglich.",
      "Clinch-Eintritt: Ellbogen beim Hereinkommen.",
      "MMA: Ellbogen aus der Top-Position auf dem Boden.",
    ],
    priorityScore: 8,
    frequencyScore: 7,
    diversityGroup: "elbow",
    videoSearchQuery: "Elbow strike Muay Thai technique tutorial",
  },

  // ─── Fortgeschritten ─────────────────────────────────────────────────────
  {
    id: "muaythai_switch_kick",
    slug: "switch-kick",
    name: "Switch Kick",
    category: "muay-thai",
    difficulty: "fortgeschritten",
    description:
      "Der Switch Kick ist ein blitzschneller Beinwechsel-Kick: Standfuß tauscht, das schwächere Bein wird zur Schlagseite. Macht den Kick explosiv und unerwartet.",
    steps: [
      "Aus der Stellung: Vorderfuß und Hinterfuß tauschen explosiv.",
      "Beim Tausch sofort der 'neue Hinterfuß' als Standfuß.",
      "Der 'neue Vorderfuß' startet einen Roundhouse.",
      "Volle Hüftrotation — wie beim normalen Roundhouse.",
      "Schienbein trifft das Ziel.",
    ],
    commonMistakes: [
      "Switch zu langsam → Gegner sieht es kommen.",
      "Tausch nicht in der Luft → kein Tempo-Gewinn.",
      "Hüftdreh halbiert → schwacher Kick.",
      "Stand nach Kick instabil.",
    ],
    usage:
      "Überraschungs-Kick mit dem schwachen Bein, das durch den Switch zum starken Bein wird. Klassische Muay-Thai-Setup-Technik.",
    equipment: ["heavy-bag", "pads"],
    relatedTechniqueIds: ["muaythai_roundhouse"],
    disciplines: ["muay-thai", "kickboxen", "mma"],
    trainingArea: ["kicks", "stand-up"],
    role: "advanced",
    level: "fortgeschritten",
    alternativeNames: ["Switch Roundhouse", "Fake-Seiten-Kick"],
    coachingCues: [
      "Switch explosiv und minimal — kein großes Hüpfen.",
      "Beide Füße tauschen fast gleichzeitig.",
      "Nach dem Switch sofort in Roundhouse-Mechanik.",
      "Überraschung ist der Kern: Geschwindigkeit vor Power.",
    ],
    safetyNotes: [],
    useCases: [
      "Überraschungs-Kick mit dem Lead-Bein.",
      "Setup: Switch-Kick zum Body + Roundhouse zum Kopf.",
      "Rhythmus-Brecher gegen reaktive Gegner.",
    ],
    priorityScore: 8,
    frequencyScore: 7,
    diversityGroup: "roundhouse",
    videoSearchQuery: "Switch kick Muay Thai tutorial",
  },

  // ─── Neue Techniken ───────────────────────────────────────────────────────
  {
    id: "muaythai_teep_counter",
    slug: "teep-counter",
    name: "Teep Counter",
    category: "muay-thai",
    difficulty: "fortgeschritten",
    description:
      "Konter-Teep: Wenn der Gegner einen Roundhouse oder einen Schritt macht, trifft ein gegenläufiger Teep den Gegner beim Eintreten. Timing schlägt Kraft.",
    steps: [
      "Gegner initiiert eine Bewegung — Roundhouse, Schritt oder Jab.",
      "Im selben Moment: Knie des Teep-Beins explosiv hochziehen.",
      "Hüfte schiebt nach vorn in die Bewegungsrichtung des Gegners.",
      "Fuß trifft den Bauch oder die Brust des reinkommenden Gegners.",
      "Gegner wird durch eigene Bewegung und den Teep zurückgeschleudert.",
    ],
    commonMistakes: [
      "Zu früh oder zu spät — Timing ist die einzige Schwierigkeit.",
      "Knie nicht hoch genug angezogen → schwacher Gegendruck.",
      "Hüfte nicht mit nach vorn → kein Stopp-Effekt.",
      "Stützbein steif beim Konter.",
    ],
    usage:
      "Defensiver Gegenkick, der den Angreifer in seinem eigenen Angriff stoppt. Sehr effektiv gegen Druckgegner.",
    equipment: ["heavy-bag", "pads", "bodyweight"],
    relatedTechniqueIds: ["muaythai_teep", "muaythai_roundhouse"],
    disciplines: ["muay-thai", "kickboxen", "mma"],
    trainingArea: ["kicks", "defense"],
    role: "advanced",
    level: "fortgeschritten",
    alternativeNames: ["Stop Kick", "Counter Front Kick", "Gegenkick"],
    coachingCues: [
      "Timing: Kick trifft während der Gegner noch in Bewegung ist.",
      "Knie hochziehen ist die wichtigste Vorbewegung.",
      "Hüfte nach vorn: nicht warten, sondern entgegengehen.",
      "Weniger Kraft nötig: Gegner bewegt sich in den Kick.",
    ],
    safetyNotes: [],
    useCases: [
      "Konter gegen Roundhouse-Kick.",
      "Stop-Kick gegen angreifende Gegner.",
      "Punktetechnik im Wettkampf: Timing-Konter.",
    ],
    priorityScore: 8,
    frequencyScore: 6,
    diversityGroup: "front-kick",
    videoSearchQuery: "Teep counter stop kick Muay Thai tutorial",
  },
  {
    id: "muaythai_body_kick",
    slug: "body-kick",
    name: "Body Kick",
    category: "muay-thai",
    difficulty: "fortgeschritten",
    description:
      "Der gezielte Roundhouse-Kick auf den Körper — Leber, Rippen oder Solar plexus. Zermürbt die Ausdauer und bricht die Kampfkraft.",
    steps: [
      "Aus dem Stand: Standfuß dreht 90° nach außen.",
      "Schlagbein kommt in der Horizontalen — Ziel ist der Körper, nicht der Kopf.",
      "Hüfte rotiert voll, Schienbein trifft Leber oder Rippen.",
      "Oberkörper rotiert mit, freie Hand schützt den Kopf.",
      "Bein zurück oder Follow-Through mit Schlägen.",
    ],
    commonMistakes: [
      "Schlag zu hoch → trifft Arm statt Körper.",
      "Keine Hüftrotation → Schlag kommt aus dem Knie.",
      "Hände sinken während des Kicks.",
      "Nach dem Kick kein Reset der Position.",
    ],
    usage:
      "Schwerer Körperkick zum Zermürben. Auf der Leber-Seite KO-gefährlich — klassischer Atempause-Erzwinger.",
    equipment: ["heavy-bag", "pads", "bodyweight"],
    relatedTechniqueIds: ["muaythai_roundhouse", "muaythai_low_kick"],
    disciplines: ["muay-thai", "kickboxen", "mma", "fitness-kickboxen"],
    trainingArea: ["kicks", "stand-up"],
    role: "advanced",
    level: "fortgeschritten",
    alternativeNames: ["Liver Kick", "Mid-Section Kick", "Körperkick"],
    coachingCues: [
      "Ziel: Rippenbereich oder Leber — horizontaler Kick, nicht diagonal.",
      "Hüftrotation: Schienbein ist das Werkzeug, Hüfte ist der Motor.",
      "Freie Hand bleibt am Kopf — kein Senken beim Kick.",
      "Timing: nach einem Jab oder Cross, wenn Deckung oben ist.",
    ],
    safetyNotes: [
      "Im Sparring: Body Kicks nur mit angemessener Kraftdosierung.",
    ],
    useCases: [
      "Zermürben der Ausdauer über mehrere Runden.",
      "Leber-Kick als KO-Setup.",
      "Combo: Jab-Cross-Body Kick als dreiteilige Kombination.",
    ],
    priorityScore: 9,
    frequencyScore: 8,
    diversityGroup: "roundhouse",
    videoSearchQuery: "Body kick Muay Thai liver kick tutorial",
  },
];
