import type { Technique } from "../types";

export const WRESTLING_TECHNIQUES: Technique[] = [
  // ─── Anfänger ────────────────────────────────────────────────────────────
  {
    id: "wrestling_stance",
    slug: "stance",
    name: "Stance & Motion",
    category: "wrestling",
    difficulty: "anfaenger",
    description:
      "Der wrestlerische Stand: leicht abgesenkt, Hände aktiv, immer in Bewegung. Fundament für jedes Takedown und jeden Sprawl.",
    steps: [
      "Schulterbreiter Stand, ein Fuß leicht vor dem anderen.",
      "Knie weich, Hüfte abgesenkt, Rücken gerade.",
      "Hände aktiv vor dem Körper — bereit zu greifen oder abzuwehren.",
      "Gewicht auf den Fußballen, Augen am Gegner.",
      "Bewegung: gleitende Schritte, niemals kreuzen.",
    ],
    commonMistakes: [
      "Zu aufrechter Stand → leicht zu Takedown.",
      "Hände unten → Underhooks gehen verloren.",
      "Auf den Fersen → langsame Reaktion.",
      "Statisch — Wrestler ist immer in Bewegung.",
    ],
    usage:
      "Default-Position vor jedem Wrestling-Austausch. Aus der Stance werden Shots, Sprawls und Ties initiiert.",
    equipment: ["mat", "bodyweight"],
    relatedTechniqueIds: ["wrestling_level_change", "wrestling_sprawl"],
    nextTechniqueId: "wrestling_level_change",
    disciplines: ["wrestling", "mma"],
    trainingArea: ["stand-up", "takedowns"],
    role: "core",
    level: "anfaenger",
    alternativeNames: ["Wrestler Stance", "Shoot Stance", "Grundstellung"],
    coachingCues: [
      "Knie über Zehenspitzen — abgesenkte Hüfte.",
      "Hände auf Schulterhöhe, aktiv bewegen.",
      "Gewicht auf Fußballen — nie auf den Fersen.",
      "Niemals kreuzen: führender Fuß in Bewegungsrichtung zuerst.",
    ],
    safetyNotes: [],
    useCases: [
      "Ausgangsposition für alle Wrestling-Techniken.",
      "MMA: Transition zwischen Striking und Takedown.",
      "Defensiv: Sprawl aus der Stance initiieren.",
    ],
    priorityScore: 10,
    frequencyScore: 10,
    diversityGroup: "stance",
    videoSearchQuery: "Wrestling stance and motion tutorial",
  },
  {
    id: "wrestling_level_change",
    slug: "level-change",
    name: "Level Change",
    category: "wrestling",
    difficulty: "anfaenger",
    description:
      "Schnelle Höhenveränderung — die Bewegung, die jedem Takedown vorausgeht. Knie biegen, Hüfte tief, ohne den Oberkörper vorzukippen.",
    steps: [
      "Aus der Stance Knie schnell beugen.",
      "Hüfte sinkt, Oberkörper bleibt aufrecht.",
      "Hände auf Schulterhöhe, bereit den Schuss vorzubereiten.",
      "Augen bleiben am Gegner.",
      "Aufrichten ohne Hüfte vorzukippen — sonst Sprawl möglich.",
    ],
    commonMistakes: [
      "Oberkörper kippt vor → Front-Headlock-Position.",
      "Knie nicht über die Zehenspitzen → kein wirklicher Level Change.",
      "Hände sinken ab → keine aktive Position.",
      "Vorhersehbar getelegrafiert — Gegner sprawlt.",
    ],
    usage:
      "Setup für jeden Takedown. Auch als Feint, um den Gegner zur Sprawl-Reaktion zu zwingen.",
    equipment: ["mat", "bodyweight"],
    relatedTechniqueIds: ["wrestling_penetration_step", "wrestling_single_leg"],
    nextTechniqueId: "wrestling_penetration_step",
    disciplines: ["wrestling", "mma"],
    trainingArea: ["takedowns", "stand-up"],
    role: "core",
    level: "anfaenger",
    alternativeNames: ["Level Drop", "Absenken"],
    coachingCues: [
      "Knie biegen, Oberkörper aufrecht — nicht beugen.",
      "Explosiv und unvorhersehbar — kein Telegrafieren.",
      "Hände aktiv: nicht fallen lassen beim Level Change.",
      "Als Feint einsetzen: Level Change + Stop als Reaktionstest.",
    ],
    safetyNotes: [],
    useCases: [
      "Unmittelbare Vorbereitung für Penetration Step.",
      "Feint gegen defensive Gegner.",
      "MMA: Wechsel zwischen Schlag und Takedown.",
    ],
    priorityScore: 9,
    frequencyScore: 9,
    diversityGroup: "takedown-setup",
    videoSearchQuery: "Wrestling level change technique tutorial",
  },
  {
    id: "wrestling_penetration_step",
    slug: "penetration-step",
    name: "Penetration Step",
    category: "wrestling",
    difficulty: "anfaenger",
    description:
      "Der explosive Schritt nach vorn, der die Distanz zum Gegner schließt. Der Schritt MUSS tief unter dem Schwerpunkt des Gegners landen.",
    steps: [
      "Aus dem Level Change explosiv mit dem Vorderfuß nach vorn.",
      "Vorderknie landet zwischen den Beinen des Gegners.",
      "Hüfte folgt sofort — Schwerpunkt unter dem Gegner.",
      "Hinterer Fuß kommt nach, schiebt nach vorn.",
      "Kopf bleibt aufrecht, Augen am Gegner.",
    ],
    commonMistakes: [
      "Vorderfuß zu kurz → Gegner kann sprawlen.",
      "Kopf nach unten → Front-Headlock-Risiko.",
      "Hüfte bleibt zurück → kein Drive nach vorn.",
      "Zu langsam — der Step muss explosiv sein.",
    ],
    usage:
      "Fundament jedes Single- oder Double-Leg-Takedowns. Wer den Penetration Step nicht beherrscht, scheitert an jedem ernsthaften Gegner.",
    equipment: ["mat"],
    relatedTechniqueIds: ["wrestling_single_leg", "wrestling_double_leg"],
    nextTechniqueId: "wrestling_single_leg",
    disciplines: ["wrestling", "mma"],
    trainingArea: ["takedowns"],
    role: "core",
    level: "anfaenger",
    alternativeNames: ["Shoot Step", "Drive Step", "Schuss-Schritt"],
    coachingCues: [
      "Vorderknie landet tief zwischen die Beine — nicht davor.",
      "Kopf aufrecht: Augen am Gegner, nie nach unten.",
      "Hüfte sofort nachziehen — kein Hintertreffen.",
      "Explosivität: der Schritt muss überraschend kommen.",
    ],
    safetyNotes: [],
    useCases: [
      "Direkter Einstieg für Single-Leg oder Double-Leg.",
      "Drill: Penetration Step + Aufstehen, ohne Takedown-Finish.",
      "MMA: Entscheidungsmoment beim Schuss-Angriff.",
    ],
    priorityScore: 10,
    frequencyScore: 9,
    diversityGroup: "takedown-setup",
    videoSearchQuery: "Wrestling penetration step drill tutorial",
  },
  {
    id: "wrestling_sprawl",
    slug: "sprawl",
    name: "Sprawl",
    category: "wrestling",
    difficulty: "anfaenger",
    description:
      "Die Anti-Takedown-Bewegung. Hüfte schießt explosiv nach hinten und unten, Hände kontrollieren den Kopf des Schussversuchs.",
    steps: [
      "Beide Beine explosiv nach hinten schießen.",
      "Hüfte fällt nach unten auf den Gegner.",
      "Hände drücken den Kopf des Gegners zur Matte.",
      "Brust auf den Schultern des Gegners — Druck nach vorn.",
      "Aus der Sprawl-Position weiterarbeiten (Front-Headlock, Whizzer, etc.).",
    ],
    commonMistakes: [
      "Hüfte bleibt oben → Gegner kommt rein.",
      "Beine zu langsam → erst halb gesprawlt.",
      "Hände nicht am Kopf → kein Druck nach unten.",
      "Brust nicht auf den Schultern → Gegner steht auf.",
    ],
    usage:
      "Erste und wichtigste Verteidigung gegen jeden Takedown-Versuch. Wer nicht sprawlt, geht zu Boden.",
    equipment: ["mat", "bodyweight"],
    relatedTechniqueIds: ["wrestling_stance", "wrestling_single_leg"],
    disciplines: ["wrestling", "mma"],
    trainingArea: ["takedown-defense"],
    role: "core",
    level: "anfaenger",
    alternativeNames: ["Sprawl Defense", "Anti-Takedown"],
    coachingCues: [
      "Hüfte explosiv nach hinten und unten — nicht nur nach hinten.",
      "Brust auf die Schultern des Gegners: Körpergewicht ausnutzen.",
      "Hände kontrollieren den Kopf: nach unten und zur Seite.",
      "Direkt Folgeaktion: Front-Headlock oder aufstehen.",
    ],
    safetyNotes: [],
    useCases: [
      "Takedown-Abwehr gegen Single-Leg und Double-Leg.",
      "MMA: Sprawl + Back Take oder Punches von oben.",
      "Drill: Partner schießt, Sprawl-Reaktion trainieren.",
    ],
    priorityScore: 10,
    frequencyScore: 9,
    diversityGroup: "takedown-defense",
    videoSearchQuery: "Wrestling sprawl takedown defense tutorial",
  },
  {
    id: "wrestling_single_leg",
    slug: "single-leg",
    name: "Single-Leg Takedown",
    category: "wrestling",
    difficulty: "anfaenger",
    description:
      "Klassischer Takedown: ein Bein des Gegners greifen, kontrollieren, zu Boden bringen. Die meistgenutzte Wrestling-Technik im MMA.",
    steps: [
      "Aus dem Penetration Step ein Bein des Gegners umklammern.",
      "Eigener Kopf an die Innenseite des Oberschenkels.",
      "Beide Hände hinter dem Knie zu einem Lock greifen.",
      "Hüfte ankreuzen — eigene Hüfte an die Hüfte des Gegners.",
      "Finish: Trip, Run-the-Pipe oder Lift-and-Dump.",
    ],
    commonMistakes: [
      "Kopf außen → Gegner kann Sprawl + Whizzer einsetzen.",
      "Eigene Hüfte zu weit weg → kein Druck nach vorn.",
      "Bein ohne festen Lock → Gegner schiebt es weg.",
      "Kein klares Finish → der Single bleibt stehen.",
    ],
    usage:
      "Standard-Takedown auf jedem Niveau. Im MMA besonders gegen die Wand effektiv.",
    equipment: ["mat"],
    relatedTechniqueIds: ["wrestling_double_leg", "wrestling_penetration_step"],
    nextTechniqueId: "wrestling_double_leg",
    disciplines: ["wrestling", "mma"],
    trainingArea: ["takedowns"],
    role: "core",
    level: "aufbau",
    alternativeNames: ["Single Leg", "High-C", "Einbein-Takedown"],
    coachingCues: [
      "Kopf innen — immer auf der Innenseite des Beins.",
      "Lock hinter dem Knie: fest, kein Rutschen.",
      "Hüfte ankreuzen: eigene Hüfte zum Gegner.",
      "Finish wählen: Trip, Run-the-Pipe oder Elevator.",
    ],
    safetyNotes: [],
    useCases: [
      "Standard-Takedown aus der Clinch-Situation.",
      "Aus dem Stand nach einem Feint oder Level Change.",
      "MMA: Single-Leg zur Wand → Finish oder Back Take.",
    ],
    priorityScore: 10,
    frequencyScore: 9,
    diversityGroup: "takedown",
    videoSearchQuery: "Single leg takedown wrestling tutorial",
  },
  {
    id: "wrestling_double_leg",
    slug: "double-leg",
    name: "Double-Leg Takedown",
    category: "wrestling",
    difficulty: "anfaenger",
    description:
      "Der explosive Takedown durch beide Beine. Tiefer Schuss, Schulter im Bauch des Gegners, beide Beine fest umklammert.",
    steps: [
      "Penetration Step tief unter den Gegner.",
      "Schulter trifft den Bauch/die Hüfte des Gegners.",
      "Beide Arme umklammern beide Beine direkt unter dem Knie.",
      "Kopf hoch, Rücken gerade — niemals den Kopf senken.",
      "Drive vor und seitlich → Gegner geht auf den Rücken.",
    ],
    commonMistakes: [
      "Kopf gesenkt → Guillotine-Risiko, besonders im MMA.",
      "Zu hoher Schuss → Gegner sprawlt sofort.",
      "Beine nur an den Knöcheln gegriffen → wenig Kontrolle.",
      "Drive seitlich vergessen → Gegner kann nicht zu Boden gebracht werden.",
    ],
    usage:
      "Volle Power-Takedown. Gegen statische Gegner oder nach einem Setup wie einem Snap-Down sehr stark.",
    equipment: ["mat"],
    relatedTechniqueIds: ["wrestling_single_leg"],
    nextTechniqueId: "wrestling_snap_down",
    disciplines: ["wrestling", "mma"],
    trainingArea: ["takedowns"],
    role: "core",
    level: "aufbau",
    alternativeNames: ["Double Leg", "Double", "Doppelbein-Takedown"],
    coachingCues: [
      "Tiefer Schuss: unter den Schwerpunkt des Gegners.",
      "Kopf IMMER hoch — Guillotine-Prävention.",
      "Griff unter dem Knie, nicht an den Knöcheln.",
      "Seitlicher Drive: Gegner wird nicht nur nach hinten geworfen.",
    ],
    safetyNotes: [
      "Im MMA: Kopf nie senken beim Double-Leg — Guillotine-Gefahr.",
    ],
    useCases: [
      "Power-Takedown gegen statische Gegner.",
      "Nach Snap-Down oder Clinch-Setup.",
      "MMA: Double-Leg + Cage für maximale Kontrolle.",
    ],
    priorityScore: 10,
    frequencyScore: 8,
    diversityGroup: "takedown",
    videoSearchQuery: "Double leg takedown wrestling tutorial",
  },

  // ─── Fortgeschritten ─────────────────────────────────────────────────────
  {
    id: "wrestling_snap_down",
    slug: "snap-down",
    name: "Snap Down",
    category: "wrestling",
    difficulty: "fortgeschritten",
    description:
      "Setup-Technik: den Gegner aus der Stellung nach vorn ziehen, oft als Vorbereitung für Front-Headlock oder Single-Leg.",
    steps: [
      "Beide Hände auf den Hinterkopf/Nacken des Gegners.",
      "Eigene Hüfte explosiv nach hinten ziehen.",
      "Gegnerischen Kopf scharf nach vorn-unten reißen.",
      "Wenn der Gegner sich krümmt → Front-Headlock fixieren.",
      "Alternativ: aus der gebeugten Position einen Single-Leg schießen.",
    ],
    commonMistakes: [
      "Kein Hüft-Pull → reines Armziehen.",
      "Hände zu hoch → kein Hebel.",
      "Snap zu früh ohne Setup → Gegner reagiert.",
      "Nach dem Snap keine Folgeaktion.",
    ],
    usage:
      "Zwingt aufrechte, defensive Gegner in eine schwächere Position. Setup für Front-Headlock-Serien oder Schüsse.",
    equipment: ["mat"],
    relatedTechniqueIds: ["wrestling_single_leg", "wrestling_double_leg"],
    disciplines: ["wrestling", "mma"],
    trainingArea: ["takedowns", "clinch"],
    role: "advanced",
    level: "fortgeschritten",
    alternativeNames: ["Head Snap", "Neck Snap"],
    coachingCues: [
      "Hüfte zieht zurück: nicht nur Arme — ganzer Körper.",
      "Hände am Nacken, nicht am Hinterkopf: mehr Kontrolle.",
      "Sofortige Folgeaktion: Front-Headlock, Shrug oder Shot.",
      "Als Rhythmusbrechertaktik: Setup für unerwarteten Schuss.",
    ],
    safetyNotes: [
      "Neck-Snaps mit Vorsicht trainieren — Halswirbelbelastung.",
    ],
    useCases: [
      "Setup für Single-Leg nach erzwungener Vorbeuge.",
      "Rhythmus-Brecher gegen defensive Gegner.",
      "MMA: Snap-Down aus dem Clinch vor einem Schuss.",
    ],
    priorityScore: 7,
    frequencyScore: 6,
    diversityGroup: "takedown-setup",
    videoSearchQuery: "Wrestling snap down front headlock tutorial",
  },

  // ─── Neue Techniken ───────────────────────────────────────────────────────
  {
    id: "wrestling_underhook_battle",
    slug: "underhook-battle",
    name: "Underhook Battle",
    category: "wrestling",
    difficulty: "fortgeschritten",
    description:
      "Das Kämpfen um Underhooks im Clinch ist die Basis des Wrestling. Wer die Underhooks kontrolliert, bestimmt die Distanz und die Aktion.",
    steps: [
      "Aus dem Clinch: einen Arm unter die Achsel des Gegners — Hüfte nahe am Gegner.",
      "Eigene Hüfte zur gegnerischen Hüfte drücken — keine Distanz.",
      "Shrug-Bewegung: eigene Schulter drückt den Arm des Gegners nach oben.",
      "Overhook des Gegners neutralisieren: Ellbogen tief, Körper drehen.",
      "Aus dem Underhook: Single-Leg schießen, Hüftwurf oder Lift.",
    ],
    commonMistakes: [
      "Arm zu flach — kein echter Underhook.",
      "Hüfte zu weit weg → Gegner kann abziehen.",
      "Kein Shrug → Overhook des Gegners bleibt dominant.",
      "Passiv im Clinch — Underhook-Kampf muss aktiv sein.",
    ],
    usage:
      "Wer Underhooks kontrolliert, kontrolliert den Kampf. Grundlage aller Clinch-Würfe und Takedowns.",
    equipment: ["mat"],
    relatedTechniqueIds: ["wrestling_single_leg", "wrestling_snap_down"],
    disciplines: ["wrestling", "mma"],
    trainingArea: ["clinch", "takedowns"],
    role: "advanced",
    level: "fortgeschritten",
    alternativeNames: ["Clinch Battle", "Pummeling", "Underhook Fight"],
    coachingCues: [
      "Hüfte nah am Gegner: Underhook funktioniert nur mit Körperkontakt.",
      "Shrug: Schulter nach oben und innen für maximalen Druck.",
      "Constant Pummeling: ständig wechseln zwischen Under- und Overhook.",
      "Aus dem Double-Underhook direkt Takedown oder Hüftwurf.",
    ],
    safetyNotes: [],
    useCases: [
      "Clinch-Dominanz: Ausgangspunkt für alle Würfe und Takedowns.",
      "MMA: Underhook-Kontrolle gegen die Wand.",
      "Drill: Pummeling-Übung mit wechselnden Griffen.",
    ],
    priorityScore: 9,
    frequencyScore: 8,
    diversityGroup: "clinch",
    videoSearchQuery: "Wrestling underhook pummeling clinch tutorial",
  },
];
